### ISSUE TITLE
ReProvision crash when Confirm pushed

### ISSUE THREAD

**Issue by The-SamminAter** [Matchstic/ReProvision#100]
**Describe the bug**
ReProvision v0.5~experimental2, iPhone 6s, iOS 10.3.3
When pushing Confirm after entering Apple ID credentials, ReProvision crashes.
This occurs when any credentials are entered.

**To Reproduce**
1. Update ReProvision to v0.5~experimental2
2. Enter any possible email address, for example j@j.j
3. Enter any possible password, for example j
4. Push Confirm

**Comment by Chriszzzlcz** [comment]
Describe the bug
ReProvision v0.5~experimental1 
iPhone 6s, 
iOS 10.0.1
When pushing Confirm ReProvision crashes.
This occurs when any credentials are entered.

**Comment by Abductist** [comment]
Describe the bug
ReProvision v0.5~experimental2
iPad 2
iOS 9.3.5
Doesn't give option to enter any credentials and always crashes when pressing confirm.
Phoenix installed through Xcode and iOS App Signer

**Comment by mrkiko** [comment]
Hi guys!
I am using an iPhone SE (N96AP) with iOS 12.3, and VoiceOver accessibility enabled. The App didn't crash after pressing Confirm, and the login process worked fine.
It crashed while re-signing, but the re-signing process seemed to go well in any case.

Thank you very very much for your work guys!!

**Comment by titi2107** [comment]
Pareil pour moi quand je clique sur confirmer l’appl Crash
iPhone X iOS 11
Une solution ?

**Comment by The-SamminAter** [comment]
> Hi guys!
> I am using an iPhone SE (N96AP) with iOS 12.3, and VoiceOver accessibility enabled. The App didn't crash after pressing Confirm, and the login process worked fine.
> It crashed while re-signing, but the re-signing process seemed to go well in any case.
> 
> Thank you very very much for your work guys!!

What version or ReProvision?  0.5~experimental1,  0.5~experimental2, or  0.5~experimental3?

**Comment by The-SamminAter** [comment]
On ReProvision `0.5~experimental3`, the application no longer crashes when `Confirm` is pushed, and appears to sign applications properly. Out of three applications though, it appears to only have installed two out of the three applications. Strangely enough, the third application is still openable, which may be because of tweaks such as AppSync Unified (if that's possible), or it may just be a bug that I'm not seeing three applications signed with Development certificates.

**Comment by The-SamminAter** [comment]
Unless any issues still persist, I'm closing this issue.

**Comment by Abductist** [comment]
ReProvision 0.5~experimental3
iPad 2
iOS 9.3.5
I am now able to type in credentials but app still crashes when I press confirm

**Comment by mrkiko** [comment]
On Tue, 12 Nov 2019, Sam wrote:

> Date: Wed, 13 Nov 2019 00:33:22
> From: Sam <notifications@github.com>
> Reply-To: Matchstic/ReProvision
>     <reply@reply.github.com>
> To: Matchstic/ReProvision <ReProvision@noreply.github.com>
> Cc: mrkiko <mrkiko.rs@gmail.com>, Comment <comment@noreply.github.com>
> Subject: Re: [Matchstic/ReProvision] ReProvision crash when Confirm pushed
>     (#100)
> 
>
>       Hi guys!
>       I am using an iPhone SE (N96AP) with iOS 12.3, and VoiceOver accessibility enabled. The App didn't crash after pressing Confirm, and the login process worked fine.
>       It crashed while re-signing, but the re-signing process seemed to go well in any case.
>
>       Thank you very very much for your work guys!!
> 
> What version or ReProvision? 0.5experimental1, 0.5experimental2, or 0.5~experimental3?
> 
Thanks very much for the follow up ! Was 0.5experimental1, with 0.5experimental5 all works great! :)
Sorry for the slowness.

Enrico

**Comment by The-SamminAter** [comment]
Re-opened because @Abductist is still having the original issue

**Comment by Matchstic** [comment]
iOS 9 crash is now fixed in 0.5~experimental4
