### ISSUE TITLE
Dark mode bug - white text invisible

### ISSUE THREAD

**Issue by aarivex** [Matchstic/ReProvision#103]
**Describe the bug**
The prompts (sign in for example) have an white background and white text, making it impossible to read descriptions and instructions.

**To Reproduce**
1. Install ReProvision on **iOS 13.2.2** with dark mode enabled
2. Wait for the sign-in prompt or open it manually by going to settings and press sign in.

**Expected behavior**
A prompt or page with clear instructions and visible text or inputs.

**Screenshots**
![CBBB74A6-5C3B-4A3E-A2A0-120932209774](https://user-images.githubusercontent.com/18628875/68715979-780ac000-05a3-11ea-82b5-97bd4d18469c.jpeg)

**Device (please complete the following information):**
- iOS 13.2.2
- iPhone X

**Comment by wxb1ank** [comment]
Same here. Also: subtitle text (ex. submitDevelopmentCSR) in the “Troubleshooting” tab is black on dark mode (where it is already on dark background — should be white).

**Comment by Matchstic** [comment]
This is now mostly fixed with version 0.5~experimental7, but there are a few more things that need some work.

**Comment by Matchstic** [comment]
All issues resolved in next update
