### ISSUE TITLE
App specific password can't use anymore?

### ISSUE THREAD

**Issue by huangjinshe** [Matchstic/ReProvision#108]
I updated to the newest version ReProvision 0.5~experimental4,  because old version keep display:
`submitDevelopmentCSR: Please update to Xcode 7.3 or later to continue developing with your Apple ID.
`

But I can't login in it.  It always display: **Failure: Your Apple ID or password is incorrect.**

I use app specific password to login before, is the new version can't use that anymore?

**Comment by Matchstic** [comment]
App specific passwords can no longer be used, due to the new API I have to use for authentication with Apple.

**Comment by huangjinshe** [comment]
@Matchstic , Thank you. But at least please display a message box to let users know. I have this issue a few days ago and finally go to the github see you commit and ask you to confirm that. I think lot of people don't know that.

**Comment by Matchstic** [comment]
I think that would be a good idea, however, I don’t get any indication from Apple’s API that the user just tried to use an app-specific password - I would have to check if the format of the password matches Apple’s, which would have the potential for false positives.

**Comment by huangjinshe** [comment]
I'm sorry, I am little confused, you mean you can check the password format?  which mean you will get the password content?   If that so , I still hope use the old school way : app specific password.

Now I even don't know the new login UI page is from Apple or App itself(there is only a little message on the bottom said: your details are only send to Apple), If users worry about the privicy they still won't use the original password.

Even if the login page is from Apple , the page content is too easy, also very easy to copy. that's a big problem for us.  I mean how do we know it's really from Apple or some bad guy just want get our ID and password?

The correct way is: you need to let user to jump to some link (If there is a apple webside could open at least or some authorize button from ios) and confirm the login page is from Apple, then we will happy to use the original password.

**Comment by Matchstic** [comment]
The login page in ReProvision is directly embedded in the app, where I have full control over the login process. I only ever pass the username and password to Apple, who then gives me a token back for subsequent logins (this is instead of saving the user’s password).

You can verify this yourself by reviewing the source code, one major reason why it is open source.

Due to the new API I’m using, I currently cannot support app-specific passwords. My guess is that this is on Apple’s side. For example, I now use exactly the same login approach that the App Store does on your device. This also doesn’t work with app-specific passwords.

**Comment by huangjinshe** [comment]
I understand that. but my point is the page is too much easy to copy from bad people, user can't confirm where it from if you don't tell or see the source(maybe some hacker publish a modified version app).  too easy to copy that kind of page you know.

My advices are:
1.If we could use the fingerprint it will much more helpfull.  (hunestly, this is the first time I saw that kind of page request my ID and password. App store always need a fingerprint).
2.Before the api support app-specific password.  Let user choice use which way to login. How about that?

**Comment by Kiaos** [comment]
Um, I am signing in to this with my real id and pass and it still says I can't use an app-specific password.
