### ISSUE TITLE
Unable to login with Unknown Error

### ISSUE THREAD

**Issue by fhc5326** [Matchstic/ReProvision#109]
**Describe the bug**
Unable to login with Unknown Error even with a clear AppleID

**To Reproduce**
Just Login

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version :10.3.3
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch) iPhone 5s(Global)

**Additional context**

**Comment by jianmingyong** [comment]
I am also facing this too.
iOS 12.4, iPhone 6

Before that, there was an error about unable to get team id with \*This is very bad\* error and now you can’t even login...

**Comment by Skimige** [comment]
Me too.
I remembered checking my certificates, and it showed 0.
After getting the `updateCurrentTeamIDWithCompletionHandler: No Team ID present! This is *really* bad.` error I signed out my Apple ID in ReProvision. Then I get the unknown error when login.
4 days left for my Chimera :(

**Comment by jihu9** [comment]
> Me too.
> I remembered checking my certificates, and it showed 0.
> After getting the `updateCurrentTeamIDWithCompletionHandler: No Team ID present! This is *really* bad.` error I signed out my Apple ID in ReProvision. Then I get the unknown error when login.
> 4 days left for my Chimera :(

Same sadness as u, just 2 days left for my Chimera...

**Comment by ahmedtsadek** [comment]
Same for me i was trying to sign unc0ver but got the team id error so I tried logging out then in and now I can sign in failure unkown error

**Comment by techandgamer** [comment]
![D95C1993-8233-4F28-8ECE-D1CE45E80B22](https://user-images.githubusercontent.com/58149914/69501376-3f87b200-0ed2-11ea-99e2-f4c3dc0e5462.jpeg)

**Comment by Matchstic** [comment]
I'm working on this, no ETA. However, progress is good so far!

**Comment by Matchstic** [comment]
Fixed with 0.5~experimental5
