### ISSUE TITLE
Way to fix the newest problem

### ISSUE THREAD

**Issue by NyaMisty** [Matchstic/ReProvision#110]
Insert this before you call any AuthKit service
[[AKDevice currentDevice] setServerFriendlyDescription:@"<iMac11,3> <Mac OS X;10.10.4;14E46> <com.apple.Xcode/217>"];
Everything goes fine

**Comment by NyaMisty** [comment]
Oh also don't forgot to change the X-MMe-Client-Info header in your populateHeaders function

**Comment by NyaMisty** [comment]
In fact AAPL is only restricting client with "iPhone" / "iPad" in the client description. 
Next potential point to check ReProvision (Apple currently not applied) is to check the capp in the GsRequest, which will require far more work for AAPL :)

**Comment by NyaMisty** [comment]
NOTE: 
- the existing accounts that logged in should be signed out. 
- every app launch we should set the same description (i.e. you should put this code in the AppDelegate)

**Comment by Matchstic** [comment]
Thanks, ended up taking an approach that migrates away from private API usage. See commit 381e4445defccfc9e9399bd58963983f10f843b4
