### ISSUE TITLE
cannot sign in after updating to experimental-4

### ISSUE THREAD

**Issue by nate-moo** [Matchstic/ReProvision#112]
`**Describe` the bug**
 Cannot sign in on experimental-4

**Expected behavior**
Ability to sign in

**Screenshots**
![571FB418-E7E5-4714-9152-C40BE1D646BA](https://user-images.githubusercontent.com/40650681/69563780-b6c74f80-0f7f-11ea-99df-05ad693876ce.jpeg)
.

**Device (please complete the following information):**
 - iOS Version IOS 12.4
- Device iPhone 8

**Additional context**

**Comment by Matchstic** [comment]
This is now fixed fully with version 0.5~experimental7
