### ISSUE TITLE
Error UpdateCurrentTeamIDWithCompletionHandler: No Team ID present! This is *really* bad.

### ISSUE THREAD

**Issue by havok225** [Matchstic/ReProvision#118]
Every time I go to resign something I get this error message

![57D0F131-A4DC-4F83-B82F-7F309B137835](https://user-images.githubusercontent.com/58230945/69662840-53eabc80-1042-11ea-9feb-818ae5595f7a.png

 -IOS 12
-iPhone 7

Started about 3-4 days ago

**Comment by disassembly** [comment]
Same problem here.

**Comment by Matchstic** [comment]
This is now fixed fully with version 0.5~experimental7

**Comment by ijandc** [comment]
iPhoneXR iOS12.4 0.5~experimental8 got the same issue!

**Comment by Greigh** [comment]
I have this same thing with 0.5~release.

**Comment by Mondster** [comment]
issue is resurfacing. unable to use reprovision to sign app.

**Comment by Mondster** [comment]
sign out and unable to sign in.

**Comment by JackGasoline** [comment]
I have the same issue at the moment!

**Comment by hackins** [comment]
iphone 6 plus 12.4 cannot sign in after logging out because of the no team id error, reprovision was experimental 8, updated to release version - no difference
there was no device in certificate list

**Comment by havok225** [comment]
Yeah the problem has resurfaced for me as well.

**Comment by pigpen2** [comment]
After updating ReProvision to 0.5.1~EOL version, i receive the message:
 "Alert - ReProvision has been broken by changes at Apple. Please use another service."
Does it means that ReProvision will never be fixed?
Any suggestion for another "service"?
Thanks

**Comment by Whom-m0rty** [comment]
In reprovision settings login in your Apple id from which you signed the certificate for Impactor/Alt server. It works for me!
