### ISSUE TITLE
Re-signing works, but with an unc0ver app issue

### ISSUE THREAD

**Issue by gititwhileyoucan** [Matchstic/ReProvision#119]
Didn't see the note about not accepting twitter support until a while ago. Sorry. 

Hope someone doesn't mind wading through this and can offer some advice...

1. When I couldn't sign into ReProvision yesterday with my usual Apple ID and PW, I created a new account. This allowed me to resign for seven days. Two certificates are listed in ReProvision as before, including "undecimus" and "fun." Not sure why both we there in the first place, but they both re-signed for seven days as usual.

2. Now, opening the unc0ver app on my phone says "Untrusted Developer", listing the NEW Apple ID in its dialog box. It says "You can trust these apps in Settings", but I see no way to trust unc0ver in Trust settings now.

3. With this latest ReProvision installed (THANKS for that!), I logged out of my new free Dev credentials and back in with my old ones again. It seems to accept my old credential (fingers crossed at that point), but it then puts up a page that says "Remove a certificate", listing two. They are these:

Device: iPhone Application: ReProvision
and
Device: unknown Application: Cydia Impactor or Extender

Am I supposed to delete these? And if so, will I have to install unc0ver all over again? Not even sure how to do that if necessary.

Sorry for my confusion, but I don't see this explained in reddit posts.

**Comment by DeafEyeJedi** [comment]
Delete the iPhone application: ReProVision one because then it’ll then reinstall a fresh new one for the same device you are using right there.

The Cydia Impactor is prolly due to you installing from PC/Mac either that or you have another iDevice that you want to keep the JB on?

**Comment by gititwhileyoucan** [comment]
Thanks! The github "thang" is new to me. Not so hot on twitter either.But hey, I must have done it right in order to get your reply :) (Being seventy is starting to slow the thought processes.)

I kinda have to think about what you describe. Thanks again friend. Do you happen to play Borderlands?

**Comment by Matchstic** [comment]
@DeafEyeJedi is right; just remove the existing one for ReProvision
