### ISSUE TITLE
Workaround to easily install signed .ipa: 3uTools on PC/Mac

### ISSUE THREAD

**Issue by badger200** [Matchstic/ReProvision#120]
For some reason, Installing unc0ver ipa in Filza just got stuck forever on “installing”. Trying Karen/angelxwind “appinst” command also failed instantly with an error. 

But for some reason, **I was easily able to install the .ipa almost instantly, using 3uTools** www.3uTools.com, a free, awesome and uniquely powerful iOS device manager GUI utility. I used Windows 7 64-bit, connecting via USB Lightning cable, but I believe Mac version is also available. 💻📲

Simply connect device, wait for 3uTools home screen to display device properly, (and possibly wait 1-3 minutes if you have 300-600+ apps installed, while AppleMobileDevice.exe transfers your installed app inventory data into 3uTools), then **click Apps on the left column.** _(⚠️NOT the “Apps” on the top tab!)_

Your apps should display in a huge list view. (If not, wait/check Task Manager for evidence of device activity, you may need to wait for it to complete and return to idle.)

**Click “Install app from .ipa”** in the upper left corner of the listview, and voilá! 🎩✨✅😃

PS: I’ve never seen an app install so fast!! I couldn’t believe my eyes the first time. 

NOTE: This helped me get my first working, free developer-AppleID-signed 7 day app .ipa ever, working on my iPad Pro iOS 12.4. Then I was able to maneuver much easier to install subsequent .ipas. I’m sorry I’ve forgotten the specifics, but **this 3uTools installation method was the key to my successful activation of ReProvision** to resign my jailbreak perpetually. 🙌🏼📆🔁

**Comment by Matchstic** [comment]
Whilst this is useful information, this is supposed to only be issues and feature requests directly relating to ReProvision. It would be better to post this elsewhere!
