### ISSUE TITLE
ReProvision is not showing up on ‘open in/with’. 

### ISSUE THREAD

**Issue by totobighouse** [Matchstic/ReProvision#123]
Whenever i press the (i) button with filza, some apps pop up so i can open the file with them; i remember ReProvision was there, but i recently downloaded an .ipa file but i seems like ReProvision is not showing. 

take a look: https://imgur.com/OZbWgSL

**Comment by totobighouse** [comment]
btw i tried reinstalling, deleting and installing it again, disable all of my tweaks but none of them work.

**Comment by ZilvisUK** [comment]
I have got exactly same problem, it used to be there as an option with whom you can open the file, but now it’s gone. Did the same as u, reinstalled and all... still not there.

**Comment by HeroMCPE5** [comment]
same problem here

**Comment by Matchstic** [comment]
Please check the “more” section of the apps shown when trying to open an IPA. I have noticed it’s usually there.

**Comment by apple52026** [comment]
Hi, I can’t find open with ReProvision in more option
