### ISSUE TITLE
I tried to port the code to Mac OS, but there was an error message

### ISSUE THREAD

**Issue by yz-java** [Matchstic/ReProvision#124]
Connection to akd was interrupted!
Remote Anisette service returned an error: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.ak.anisette.xpc"

**Comment by Matchstic** [comment]
Yep, you need a specific entitlement and a patched akd on your macOS system. AltSign gets around this via using a mail plug-in to get at Anisette data.

**Comment by yz-java** [comment]
> Yep, you need a specific entitlement and a patched akd on your macOS system. AltSign gets around this via using a mail plug-in to get at Anisette data.
> […](#)
> On 6 Dec 2019, at 07:57, 怪咖 ***@***.***> wrote: ﻿ Remote Anisette service returned an error: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.ak.anisette.xpc" — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I checked akd related information and still don't quite understand. Please recommend some relevant information? Thank you

**Comment by evandrix** [comment]
https://github.com/Matchstic/ReProvision/issues/96#issuecomment-551928795

**Comment by evandrix** [comment]
but how to patch `akd`?
