### ISSUE TITLE
Crash on login experimental 8, iPod touch 5, 9.3.5

### ISSUE THREAD

**Issue by Lion4K** [Matchstic/ReProvision#125]
**Describe the bug**
The app crash when trying to login, I'm pretty sure that the user and password combination isn't wrong.

**To Reproduce**
2. Tap on '....'
4. See error.
Open app, type credentials, confirm, crash.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)

**Additional context**

**Comment by Matchstic** [comment]
Duplicate of #113
