### ISSUE TITLE
Error：This action could not be completed. Try again.

### ISSUE THREAD

**Issue by NiuStar** [Matchstic/ReProvision#126]
**Describe the bug**
I use the method checkUsername
[[RPVAccountChecker sharedInstance] checkUsername:@"905666153@qq.com" withPassword:@"******" andCompletionHandler:^(NSString *failureReason, NSString *resultCode, NSArray *teamIDArray, NSURLCredential* credentials) {
        NSLog(@"OK %@",failureReason);
    }];
After execution, the server returns the result as :This action could not be completed. Try again.
**To Reproduce**

**Expected behavior**
return the gsToken

**Screenshots**

**Device (please complete the following information):**
 - iOS Version
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)

**Additional context**

Can you help me? Thank you very mach

**Comment by NiuStar** [comment]
I try by your code，but donot work through。
The worning infomation is ：This action could not be completed. Try again.

My iOS is not Prison break。

I try the macos ，it is same error。
I need your help，thanks

**Comment by Matchstic** [comment]
This code absolutely requires private entitlements to gain access to Anisette data from AuthKit. This is added to every request to Apple, and identifies your device to their servers. You need a jailbreak for this.

**Comment by NiuStar** [comment]
I ran the code with macos ， the error is same。

**Comment by NiuStar** [comment]
I want run it by macos，how can i do it？
I see such message，the machine need patch，what can i do it？
Thanks。

Now ，I build a system to sign for normal ios，I can install ipa for device by the device self，do not need Safari and allow it。I just need sign the  ipa by free developer cert。now，I need your help，thanks。

**Comment by Matchstic** [comment]
Honestly, I don’t know how to get it working on macOS. You’re likely going to need a similar approach to AltServer - use a mail plugin to get Anisette data over IPC, avoiding the need to communicate with akd in the app itself.

**Comment by NiuStar** [comment]
sorry,i can't find any article about  'use a mail plugin to get Anisette data over IPC' , where is the AltServer ? Is https://github.com/rileytestut/AltServer?

**Comment by Matchstic** [comment]
I’m just trying to give you a direction to start from, based off work someone else has done. I don’t have the answers you’re looking for.
