### ISSUE TITLE
Cannot sign, reprovision not working at all

### ISSUE THREAD

**Issue by cyntrifical** [Matchstic/ReProvision#127]
**Describe the bug**
Reprovision was working and then the following week it just stopped and now even after revoking all certificates and even logging into another account it keeps saying error and won’t sign anything whatsoever. 
**To Reproduce**
1. Wish I could say, i don’t know why or how this started but guess its back to reinstalling u0 every week.....

**Expected behavior**
Pretty cut and dry.....do nothing, reprovision just signs app and life goes on

**Screenshots**
Not necessary? Self explanatory

**Device (please complete the following information):**
 - iOS Version - 12.4
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch) - iPhone 8, 64gb

**Additional context**
Please let me know if there’s anything you need me to get to help resolve this

**Comment by cyberfunk** [comment]
It seems like Apple broke things again. I'm getting the same behavior on latest Reprovision. iOS 11.4.1 with latest Unc0ver

**Comment by cyberfunk** [comment]
It seems like Apple broke things again. I'm getting the same behavior on latest Reprovision. iOS 11.4.1 with latest Unc0ver

**Comment by Matchstic** [comment]
I can’t reproduce this; I’m seeing zero issues with signing apps.

Please post the error message.

**Comment by cyberfunk** [comment]
You're right matchstic. My issue was a bad preference file from an old Jailbreak. I deleted preferences using icleaner pro and was able to sign apps again.
