### ISSUE TITLE
Crash with sign in the apple ID

### ISSUE THREAD

**Issue by Albaraa2002** [Matchstic/ReProvision#128]
ReProvision after update version (0.5~experimental8), I open ReProvision and want to sign in, after input my apple id and password I press confirm and ReProvision crash.
I also tried to reinstall ReProvision , remove and reboot and then install but still crash after confirm.

 - iOS 9.3.6
- Device ( iPhone 4s )

**Comment by Matchstic** [comment]
Duplicate of #113
