### ISSUE TITLE
Where is the akd's path?

### ISSUE THREAD

**Issue by NiuStar** [Matchstic/ReProvision#131]
**Describe the bug**

Where is the akd's path?
/System/Library/PrivateFrameworks/AuthKit.framework/akd is NULL
I want to dlopen it , but i con't find it in my iphone with ios12.4, please help me , thankss.

**Device (please complete the following information):**
 - iOS Version 12.4
- Device ( iPhone)

**Comment by Matchstic** [comment]
It’s stored in the dyld_shared_cache. Because it’s a runnable executable, not a dylib, you can’t dlopen it.

**Comment by NiuStar** [comment]
> 它存储在dyld_shared_cache中。因为它是可运行的可执行文件，而不是dylib，所以您无法dlopen它。
> […](#)
> 在2019年12月21日晚上7：47，Nqc ***@***.***>写道：描述bug akd的路径在哪里？我想对其进行dlopen，但在ios12.4的iphone中找不到它，请帮助我，谢谢。设备（请完成以下信息）：iOS版本12.4设备（iPhone）-之所以会收到此消息，是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

Thank you，but，I run dlopen OK when i work in macos。

**Comment by Matchstic** [comment]
Sorry, but this isn't something I can help with!
