### ISSUE TITLE
The maximum number of apps for free development profiles has been reached.

### ISSUE THREAD

**Issue by NiuStar** [Matchstic/ReProvision#133]
**Describe the bug**
I use the free developer certificate to sign and install the application. It's OK to install both. When I install the third one, I get an error prompt: the maximum number of apps for free development profiles has been reached. Do you have any experience? How did you solve it?

**Expected behavior**
I want install app in iOS and No quantity limit

**Device (please complete the following information):**
 - iOS 9、12.4、13.3
- Device
iOS

**Comment by Matchstic** [comment]
This is an Apple restriction, that I cannot bypass.
