### ISSUE TITLE
[question] can reprovision only work as a JB Tweak?

### ISSUE THREAD

**Issue by Lion4K** [Matchstic/ReProvision#135]
I was wondering if it could work as an IPA sideload too, because that way, it could perhaps pack a side service to resign itself, and it would resign any app w/o the need to have a jailbreak running , since some JB solutions needs to be kick-started at each boot and all.
Let's say it's a less used device like a home iPad and you forget to charge it and when you do the JB solution app is unsigned and you can't sign it back for any reason at all.
Reprovision being able to run it would resign the app for you and bring peace in the jungle once more.

**Comment by Matchstic** [comment]
ReProvision requires a jailbreak; the method of installing apps locally is the problem for non-jailbroken use. This is not something I plan to look at.
