### ISSUE TITLE
Error: For 'unc0ver': listAllApplicationsForTeamID: Your se

### ISSUE THREAD

**Issue by Greigh** [Matchstic/ReProvision#138]
**Describe the bug**
The screenshot and title explain it. 

**To Reproduce**
1. Try to sign an application
2. Get error

**Expected behavior**
The application gets signed. 

**Screenshots**
![IMG_1126](https://user-images.githubusercontent.com/57759540/72390449-bf731100-36f8-11ea-80f4-c619f13a9136.jpg)

**Device (please complete the following information):**
 - iOS Version: iOS 12.4 (unc0ver)
- Device: iPhone XS Max

**Additional context**
I got this error before:
![IMG_1125](https://user-images.githubusercontent.com/57759540/72390224-30fe8f80-36f8-11ea-8ea7-dd15575e93fd.jpg)

and I logged into the Developer portal on https://developer.apple.com/ it seemed to let me login. But now I am getting the error above. This all happened after I updated my MacBook Xcode and opened it. Not sure if that's a coincidence or not.  

Edit: As I'm writing this, it is giving me this error: 
![IMG_1127](https://user-images.githubusercontent.com/57759540/72390478-d6b1fe80-36f8-11ea-9fce-120cec004823.jpg)

I will update this if it fixes it by logging back in but I doubt it.

**Comment by bewl87** [comment]
you’re not alone, i’m having the same problem. luckily after 7 tries it finally signed but on my second device it’s still not resigning. fuck you tim apple.

**Comment by thegalkin** [comment]
Upvoting, just got this issue today. I got that error, then tried to logout login and I can’t login having the same message.

**Comment by ReNaNLpArK** [comment]
Same here 😞

**Comment by zavul0n** [comment]
Ios 12.4 uncover. Same problem. It begins 1 hour ago!

**Comment by AnakinCzar** [comment]
Same!! :( wtf and I’m on my last day to expire

**Comment by zavul0n** [comment]
> Same!! :( wtf and I’m on my last day to expire

Like an alternative you can sign uncover via pc with 3utools programm. In jailbreak section inside 3utools via pc.

**Comment by laithayoub71** [comment]
I’m also having the same problem... Any solution yet?

**Comment by zavul0n** [comment]
> I’m also having the same problem... Any solution yet?

Only - Like an alternative you can sign uncover via pc with 3utools programm. In jailbreak section inside 3utools via pc.

**Comment by laithayoub71** [comment]
Or AltDeploy. It’s a great alternative but it’s for Mac only. I have a mac
and to anyone else who has one, I recommend using it.

**Comment by jonesmith518** [comment]
same problem, i'll give altDeploy a try tonight

**Comment by kevjeff7** [comment]
Yep shes not working

**Comment by hawklord13** [comment]
Got the same problem

**Comment by zenodalla** [comment]
got the same problem

**Comment by techandgamer** [comment]
Sorry that this isn’t related, but would you mind sharing what the tweak is for your iPhone XS Max status bar Greigh?

**Comment by jonesmith518** [comment]
altDeploy works on xr 12.4

**Comment by Greigh** [comment]
> Sorry that this isn’t related, but would you mind sharing what the tweak is for your iPhone XS Max status bar Greigh?

NiceBarX from NiceiOS. It does cost. But it is so worth its price.

**Comment by OneSpecky** [comment]
Same goes to me. Please please kindly fix it dear dev. Thanks

**Comment by dylanwer10** [comment]
I'm getting the same issue, hopefully this is fixed soon.

**Comment by 8a5** [comment]
Got an update in Cydia for Reprovion 0.51-EOL, after opening got this message:

![177412AD-E953-4196-9686-1A04DF263F48](https://user-images.githubusercontent.com/11342933/72628752-415c7780-394f-11ea-9e4e-6172df08b695.png)

**Comment by smokinglala** [comment]
I didn’t delete ReProvision. And every now and then it asks to unlock to reinstall. And today it said successful for one of them. Maybe there’s still something that can be done?

![78BF75CF-A3B4-494A-A1EF-BDD682E6373D](https://user-images.githubusercontent.com/41111279/73131649-e4954700-4049-11ea-8760-c0fd4a20675f.png)

**Comment by as714xx** [comment]
I am on ios 13.2.3 iPhone Xr and have the same issue
![6AA33AF9-A609-48FE-8C1B-3BF85748CFBF](https://user-images.githubusercontent.com/55059978/79412874-54d1ab80-7f5b-11ea-9377-df75d4505dab.jpeg)
Help
