### ISSUE TITLE
Login Failure using iOS 9.3.5

### ISSUE THREAD

**Issue by theLaxerz** [Matchstic/ReProvision#140]
iOS 9.3.5 Jailbroken with Pheonix, which is what I am trying to sign as the Signing Services are not exactly reliable now. It would be great if you could develop a desktop version. But when signing in with this Version I am not able to login says Login Invalid.

**Comment by Cr4nkSt4r** [comment]
A desktop version wouldn't change anything, because Apple changed something on their side, therefore, the desktop app would also need an update, same goes for the iOS app.
So please, be patient, until the update gets released.

**Comment by theLaxerz** [comment]
oh it changed the ability to login, so devices I have logged in are good interesting.
