### ISSUE TITLE
Login failed , no internet connection - Chinese version

### ISSUE THREAD

**Issue by xxSkyy** [Matchstic/ReProvision#141]
Hello
I've got same problem as #80 but their link not works anymore. 
TL;DR I can't allow app internet connection cause no prompt of it. Chinese versions of iPhone has feature that you can allow app connecting to the internet with wifi or wifi and mobile data or just totally block. And by default iPhone is blocking internet access for app so I can't login.
Can anyone please upload/reupload this fix to me?

**Comment by Cr4nkSt4r** [comment]
Since Apple changed something on their end, you can't login at all.
So please, be patient, until the update gets released.

**Comment by xxSkyy** [comment]
@Cr4nkSt4r sure I will wait, but still I wont be able to if there wont be a prompt to allow internet connection for app.
