### ISSUE TITLE
[Question] There's no way to convince you to keep working on this?

### ISSUE THREAD

**Issue by Lion4K** [Matchstic/ReProvision#142]
Your's is the only tweak of the kind for older 32bit devices, there's alternatives for 64bits but not for older 32bits.

I mean, at least update for those with older devices.
That would be less stressful to you, no?

Please?
Pretty please?
Pretty pretty please?

**Comment by zenodallavalle** [comment]
Other tweaks for 64bit devices would be?

**Comment by isja693** [comment]
You would have to follow the below every 6 days

https://www.youtube.com/watch?v=fK6yEvn1RgM&feature=youtu.be

**Comment by Matchstic** [comment]
Sorry, but I won’t be updating it; there’s not anything that can convince me otherwise. The issue is that Apple is progressively locking down their signing API so that only real Macs can contact it. As a result, anything that is done to workaround this can be patched.

**Comment by Lion4K** [comment]
I understand.
Well, thank you very much for all your time spent with us, we really appreciate it!
