### ISSUE TITLE
The end?

### ISSUE THREAD

**Issue by JackGasoline** [Matchstic/ReProvision#143]
So, is this the end for ReProvision? Thanks to @Matchstic for making this app possible all this time!

Can anyone recommend an alternative?

**Comment by disassembly** [comment]
Sign failed again, and update reprovision, re-launch it and what?!?!
Alert!! Damn apple!

**Comment by DeerSpotter** [comment]
[ReProvisionDebug.txt](https://github.com/Matchstic/ReProvision/files/4081506/ReProvisionDebug.txt)


Please see debug text from ReProvision. Could we somehow run the same verification through a custom server side respond? Can we emulate the Apple servers? Like a man in the middle to get the verification for our devices?
