### ISSUE TITLE
It may still work?

### ISSUE THREAD

**Issue by smokinglala** [Matchstic/ReProvision#144]
I kept ReProvision with hopes it can work someday. Today when asked to unlock my phone. One of them, said success. Really
Odd. Of course I can’t see if it works cause I am using the eol version 

![710DA1EB-3186-4ED4-9004-FD4CE97E9826](https://user-images.githubusercontent.com/41111279/73131664-4eadec00-404a-11ea-947a-df81fe111113.png)

**Comment by salem77sr7** [comment]
> I kept ReProvision with hopes it can work someday. Today when asked to unlock my phone. One of them, said success. Really
> Odd. Of course I can’t see if it works cause I am using the eol version
> 
> ![710DA1EB-3186-4ED4-9004-FD4CE97E9826](https://user-images.githubusercontent.com/41111279/73131664-4eadec00-404a-11ea-947a-df81fe111113.png)
