### ISSUE TITLE
Unsigned app signing 

### ISSUE THREAD

**Issue by eglacias** [Matchstic/ReProvision#152]
Still staying with iOS 12.4 for a good reason, I can run checkra1n and then install uncover directly from filza  successfully, and it will run, but of course it’s not signed and has no profile. Now if I could only sign it, I am no longer dependent on finding a volatile web link to use it.  This allows temporary on device rejailbreak until I get to a computer to run checkra1n. 
 Since this app already works by replacing a profile, could it not select IE unc0ver installed application and give it that profile anew?

**Comment by Matchstic** [comment]
Instead of going through that hassle, just install unc0ver with ReProvision - go to its website in Safari, download the IPA, and open it in ReProvision from there.

**Comment by eglacias** [comment]
Oh, that’s silly. I didn’t realize that open with reprovision actually existed in this way! Problem solved, also I can "open with" directly from Filza as well and sign apps!
