### ISSUE TITLE
Scrolling cert text

### ISSUE THREAD

**Issue by g0sbv** [Matchstic/ReProvision#155]
**Describe the bug**
Just noticed on my 5s the cert text scrolls science.xnu.undecimus yet on my iphone x and iphone 7 plus it is static manualy sign fine just wondered if this means anything or just ignore it.
**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)

**Additional context**

**Comment by Matchstic** [comment]
That's just part of the UI - its the same as when the iOS media player doesn't have enough space to show the artist/album.

**Comment by g0sbv** [comment]
cheers matt lets hope it gets to no1...still love it
Ricky
