### ISSUE TITLE
ReProvision crash

### ISSUE THREAD

**Issue by acegoal07** [Matchstic/ReProvision#162]
**Describe the bug**
ReProvision crashes when you import the ipa you want to install is copied into ReProvision to be signed. Also when you try and resign apps with ReProvision it says it is unable to find the file.

**To Reproduce**
1. Go to 'any where you have a ipa stored'
2. Tap on 'copy to ReProvision’

**Expected behavior**
Menu pops up saying install and I would then press the install button and then it’s done
**Device (please complete the following information):**
 - iOS 13.5
- IPhone XR

**Comment by Matchstic** [comment]
Not planning to fix this
