### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by VeryNiceUsername0924** [Matchstic/ReProvision#165]
**Describe the bug**
Whenever I try to install the package, I get
"unable to create 'Base.iproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib/objects-13.0+.nib"
I'm not out of space on my root partition, and I get the same error if I try to install it through apt-get directly.

**To Reproduce**
Try to install it, and have bad luck

**Expected behavior**
It installs (lol)

**Device (please complete the following information):**
iPhone 5C, iOS 10.3.3 w/ h3lix jailbreak

**Comment by Matchstic** [comment]
Sorry, I’m not going to fix this
