### ISSUE TITLE
Problem signing Uncover

### ISSUE THREAD

**Issue by J0rd40** [Matchstic/ReProvision#169]
**Describe the bug**
Can’t sign uncover, image attached.
![82035BF4-DDB2-4CAD-B22E-151169C287B7](https://user-images.githubusercontent.com/23746129/91170980-9c1e3480-e6d1-11ea-87a9-c11e0fb67abb.png)

**To Reproduce**
2. Tap on '....'

**Expected behavior**

Even after deleting everything, certificates, and not having a single app, it shows this!
**Screenshots**

**Device (please complete the following information):**
 - iOS Version
13.4
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)
iPhone 11

**Additional context**

**Comment by J0rd40** [comment]
It works with Appsync Unified. It signs Uncover with success.

**Comment by Matchstic** [comment]
Sorry, ReProvision is no longer supported. Use AltStore instead.

**Comment by J0rd40** [comment]
If the phone goes dead. I start it, then I try to open the signed apps in normal state, and then the “signed” apps crash.

**Comment by J0rd40** [comment]
Altstore doesn’t have in phone signing?
