### ISSUE TITLE
Electra1131 Won't be able to resign again after 6-7 days...

### ISSUE THREAD

**Issue by DeafEyeJedi** [Matchstic/ReProvision#47]
Noticed it wasn't working to resign Electra1131 after 6-7 days and once I have troubleshooted this down to the point where I just decided to sign out and re sign in through the ReProvision Tweak and then clicked on to resign which worked flawlessly. It seems to be a pattern to work after the first try but then a week later it just stops working until I sign out of RePro Tweak and vice versa. 

Let me know if I be more of help... Thanks for this amazing tweak! 

This was done on iPhone 6S Plus and the same phenomenal issue appears on the iPad Mini 2 as well as my older iPhone 6S (that I use as an iPod touch) in case you were curious.

**Comment by Matchstic** [comment]
Is there any error messages given if you enable Debug Alerts at all?

**Comment by DeafEyeJedi** [comment]
Thought about giving that a try. But then I decided just to uninstall it and reinstall this tweak again. Ran a test and it signed twice whenever I pressed 'sign' periodically over the weekend. 

Now the question is does it do it automatically on its own per option that I selected in settings (resign 2 days in prior is the one I chose) and will let you know at the end of this week on whether or not it works. Pretty sure it'll be all fine and dandy! 

Thanks for checking in...

**Comment by DeafEyeJedi** [comment]
Hello again. After smooth sailing for the past few weeks with this wonderful tweak. I allowed myself into a situation where my iPhone had died not realizing it wasn't charging properly after plugging it in at 2% thinking it was charging. Been through it all when it comes to side loading apps such as Electra via Cydia Impactor. However this is the first time Im seeing an error showing up saying this...

![screen shot 2018-09-15 at 10 20 44 am](https://user-images.githubusercontent.com/22017443/45588927-eb4a7080-b8d1-11e8-8a98-4808c064a719.png)

Which brings me here to tell you what would be the next time for me to do AFTER I've tried revoking all apps on my developer account as well as deleting electra app on my iPhone? Currently got myself back in JB mode after side loading Electra via AppValley (not a fan of this TBH as I don't support piracy) but it was the only way for me to get back into it in order for me to delete the ReProvision tweak thinking it would do the trick with the error above to no avail after several failed attempts.

**Comment by Matchstic** [comment]
Hi,

I’m working on this right now! Building a desktop app for it, as Impactor only revokes it’s own certificates.

Matt

**Comment by DeafEyeJedi** [comment]
Excellent! That's great to hear and thanks Matt for all that you do to make this possible on our end.

**Comment by DeafEyeJedi** [comment]
Correct. You're damn quick for one and secondly I admire the beauty yet so simple to use. Extremely intriguing to have this desktop app as an alternative solution in the back of our minds. So happy! 

![screen shot 2018-09-15 at 3 38 56 pm](https://user-images.githubusercontent.com/22017443/45591164-329b2600-b8ff-11e8-9773-55259aa2accf.png)

![screen shot 2018-09-15 at 3 39 21 pm](https://user-images.githubusercontent.com/22017443/45591165-3c248e00-b8ff-11e8-9db8-fa67a6fef1b6.png)

I was able to revoke the rest of certificates that were unable to see from Apple Developer's settings and then delete the electra from AppValley while keeping the original Electra (from using Impactor) and voila now I have a clean and legit JB once again. 

![img_6374](https://user-images.githubusercontent.com/22017443/45591166-4777b980-b8ff-11e8-8ea5-03315b1f25c6.PNG)

Mad props to you, Matt!

**Comment by Matchstic** [comment]
Excellent, that’s great to hear! I can now look at getting the Windows and Linux versions built tomorrow, then can have a general release of the first public beta provided they also work as expected.

I didn’t build this all today though. ;P I’ve been working on this app for a week, started last weekend then picked it up again this evening.

**Comment by DeafEyeJedi** [comment]
Well thanks for catching this bug sooner rather than later. I just have been relieved with the magic that your tweak provides on a weekly basics unless the battery dies out on me which hardly ever does. 

Though I try to cycle it once a month or two if I can. BigBoss just released a beta of 'SafeShutdown' tweak which seems quite interesting to the very least. 

Best of luck on getting the first public beta for all three running OS's. Excellent work as always, Matt!
