### ISSUE TITLE
App doesn't log in

### ISSUE THREAD

**Issue by JuegOStrower** [Matchstic/ReProvision#48]
**Describe the bug**
Can't login with apple id. It says it failed to get a certificate for the server. My internet works ok. It happens after I put my application password from Apple. It is the Apple Id that I used with Impactor. Everything works ok on my device.

**To Reproduce**
1. Log in
2. See error

**Expected behavior**
Application has to log in

**Screenshots**
![img_0015](https://user-images.githubusercontent.com/12816832/44493746-8e93c700-a63f-11e8-84cd-2b503af9dd5e.PNG)

**Device (please complete the following information):**
 - iOS Version: 9.3.5 (jailbroken with phoenixpwn)
- Device: iPod Touch 5g

**Comment by JuegOStrower** [comment]
Wow, it is fixed now...

**Comment by smillman1337** [comment]
> Wow, it is fixed now...

What was the fix?
