### ISSUE TITLE
can't load ipa's from safari or filza using the "Open in" feature

### ISSUE THREAD

**Issue by Burnwood1911** [Matchstic/ReProvision#52]
im on ios 10.3.3 h3lix jailbreak

when i press open in nothing happens

**Comment by Matchstic** [comment]
I’ve got conflicting reports for this; one of my testers on iOS 10.3.3 is able to use the “Open in” feature without an issue. Try using iCleaner Pro to see if it’s a tweak conflicting with that functionality.

**Comment by Burnwood1911** [comment]
Disabled all tweaks still same thing

**Comment by Matchstic** [comment]
“Open in” has now been revised
