### ISSUE TITLE
Signing is incorrect for iOS 12 and CoreTrust

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/ReProvision#56]
Support is needed for iOS 12 and its CoreTrust addition.

From #44:
- CoreTrust validation fails, requiring: LeafAnchor (APPLE_IOS_OID), correct Issuer and Certificate common names, and signed CMS data w/ full chain. 

The latter likely is missing from the embedded ldid code, and potentially requires a DER & asn1 encoded certificate instead of PKCS7

**Comment by Matchstic** [comment]
From research:

- CoreTrust validates

**Comment by Matchstic** [comment]
Very useful link: https://opensource.apple.com/source/Security/Security-58286.70.7/OSX/libsecurity_codesigning/lib/signer.cpp.auto.html

**Comment by Matchstic** [comment]
Pushed current work to the ios12-codesigning branch.

Looking at sorting the requirements mainly now.

**Comment by Matchstic** [comment]
Pushed again; am now generating the equivalent designated requirements as above, with still no luck passing CoreTrust evaulation. My guess is that the CMS signature is not correct, i.e., PKCS7_sign is not the correct function to be calling to generate it?

**Comment by malhaar** [comment]
Recheck requirements blob it doesn't contain ..
public static readonly byte[] APPLE_IOS_OID =       { 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x63, 0x64, 0x06, 0x02, 0x01 };

rest of code snippets will be sending you via mail ..

**Comment by Matchstic** [comment]
Done with commit 9a621e5f12aef2efc7a0dc8a20981c72023d1f13, thanks @malhaar ! 

Future 'gotchas'; I didn't bother trying to sort out that on iOS, the SecRequirement* symbols are not present. That is needed in the current implementation for requirements. Interestingly, iOS doesn't complain if they're not present.
