### ISSUE TITLE
Once installed on latest version, device is booted into safe mode

### ISSUE THREAD

**Issue by ethanm10** [Matchstic/ReProvision#60]

**Comment by Matchstic** [comment]
I can’t fix this without a crash log. Furthermore, ReProvision does not hook into SpringBoard whatsoever - it’s not possible for it to cause Safe Mode.

**Comment by AndiVienna91** [comment]
Same Problem here.

Once installed the Springboard crashes and there is no way out of Safe-Mode until ReProvision is deinstalled.

**Comment by Matchstic** [comment]
Again, I need a crash report to know more; I don’t have this issue occurring on any of my devices!

**Comment by AndiVienna91** [comment]
... and where can I find the Crash-Report?
