### ISSUE TITLE
[Solved] App has no network ability before it request a permission on devices selled in China

### ISSUE THREAD

**Issue by esterTion** [Matchstic/ReProvision#61]
**Describe the bug**
So there's this weird network access permission, which only China devices have. ReProvision doesn't have a chance to ask for it, so the login will only fail with no reason, just like no network at all. 

**To Reproduce**
> I'm not sure, you might need a specific device for this? 

**Expected behavior**
> It should work :)

**Screenshots**

**Device (please complete the following information):**
 - iOS 12.1.2
- iPhone 8

**Additional context**

**Comment by Namouk** [comment]
Run this command in a remote ssh session in your phone:

`rm -r /var/preferences/com.apple.networkextension* && reboot`

After you restart and jailbreak again, turn wifi/cellular off and on, then run an official app from the app store that requires internet. This will recreate the files deleted with the above command and ReProvision will be able to connect.

**Comment by esterTion** [comment]
It worked! Thanks a lot!

**Comment by Namouk** [comment]
Glad it helped!

It's a workaround but not a fix.

There must be a reason why some apps aren't able to trigger a WLAN/Mobile Data access request.

**Comment by esterTion** [comment]
yeah, I’m confused too. 
I tried to build an empty app do nothing but create an NSURLConnection, when installed as a new app it triggered, but if replaced in place there’s no request. 
Also I tried change an already granted bundle id, but no luck. 

Maybe have something to do with upgrade from old version? This phone is restored from an iOS 9.3.2 backup recently.

**Comment by BirkhoffLee** [comment]
Me too have the exact same issue, using an iPhone sold in China. The workaround works for me.

**Comment by chenmin1992** [comment]
> Run this command in a remote ssh session in your phone:
> 
> `rm -r /var/preferences/com.apple.networkextension* && reboot`
> 
> After you restart and jailbreak again, turn both wifi/cellular off and back on, then run an official app from the app store that requires internet. This will recreate the files deleted by the above command and ReProvision will be able to connect.

国行怎么了这是  Cydia没网也是这么修复
what's difference between IDevice selled in China and other countries? this method is also used to fix Cydia can not access network issue.

**Comment by Namouk** [comment]
@chenmin1992 

It actually has to do with the fact that iOS devices with Chinese model numbers are not displaying WLAN in settings, instead of WIFI.

These devices have another layer of network security that forces app to request a confirmation (access to WLAN and/or Cellular Data) from the user when they first start it for the first time.

The problem is Reprovision and other non-AppStore apps don't have that request built-in, so iOS doesn't know they want to access the network.

By manually deleting the com.apple.networkextension plist files (this is not supposed to happen, since users should never have access to the root partition) and restarting, the system recreates them and let (whitelist?) already installed and signed apps to access both WLAN and Cellular data.

**Comment by chenmin1992** [comment]
@Namouk Thank you very much for so clear explain, I now remember that Chinese officer ask Apple Inc to restrict apps to access network.

**Comment by Matchstic** [comment]
This sounds to me that the “uicache” command should be responsible for updating that plist of whitelisted apps; I’d personally treat this as a bug in the core of the jailbreak! 

I’ll forward this up to Pwn2Ownd, and see if he agrees.

**Comment by esterTion** [comment]
The weirdest thing is that, even with built-in system app, like App Store, it will still ask permission on first launch.

**Comment by Orgmist** [comment]
I’ve downloaded MTerminal and copy pasted this code 

rm -r /var/preferences/com.apple.networkextension* && reboot 

Then I hit Y 

Nothing happens no fix.. what am I doing wrong ?

**Comment by Namouk** [comment]
> @esterTion I’ve downloaded MTerminal and copy pasted this code

> Nothing happens no fix.. what am I doing wrong ?

Did your device restart?

**Comment by Orgmist** [comment]
@namouk nope.. I’ve done a similar thing to fix cydia but I ssh with my computer and dropped a network fixer. 

I’m running  iOS 12.0.1 on an iPhone 6 (Uncover)

**Comment by chenmin1992** [comment]
@Orgmist  Is your device display WLAN(无线局域网 in Chinese) or WIFI? this issue is only suitable for the IDevices sold in China.

**Comment by Orgmist** [comment]
@chenmin1992 WLAN

**Comment by chenmin1992** [comment]
@Orgmist make sure the three files whose filename start with com.apple.networkextension in /var/preferences/ deleted, reboot your device manually, after reboot, turn on WLAN, visit a website and re-jailbreak, after jailbroken, check if the issue fixed.

**Comment by esterTion** [comment]
@Orgmist
run `su` and enter root password first before `rm`

**Comment by Orgmist** [comment]
@chenmin1992 thanks a lot this worked for me ! Y’all are the best on that response time
