### ISSUE TITLE
Login can fail

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/ReProvision#64]
For some unknown reason (probably) logins can fail with a user’s Apple ID. 

I do know this can happen if the ID in question is a child account under a family account. However, Apple’s endpoint doesn’t tell users that...

**Comment by Boogs808** [comment]
I’m having this problem. Rejailbroke my device many times with no other tweaks but ReProvision Using a iPhone X on 12.1.2 Any fix or help would be great. Thanks.

**Comment by Matchstic** [comment]
Have you used Cydia Impactor before? If not, make sure to do so then login should work.

**Comment by Boogs808** [comment]
Ok thanks.

**Comment by Matchstic** [comment]
No longer valid with recent changes to authentication
