### ISSUE TITLE
ReProvision brakes rootlessJB3

### ISSUE THREAD

**Issue by mcproj** [Matchstic/ReProvision#66]
iOS 12.0.1 rootlessJB3 3.2.8 jailbreak.
Latest version ReProvision breaks rootlessJB3. 
If rootlessJB app is signed by ReProvision, then it won't be able to start dropbear. 
The same IPA signed by Cydia Impactor on a mac is working well.

**Comment by Matchstic** [comment]
Known issue, not caused by ReProvision - RootlessJB modifies it’s own application bundle after installation. Won’t be fixing this.
