### ISSUE TITLE
ReProvision would not open iOS 12.1

### ISSUE THREAD

**Issue by atDavid** [Matchstic/ReProvision#67]
Hello,
Whenever I open Reprovision v4.2, it shows a black screen and stays frozen until the device resprings.
I am jail broken on an iPad Air using unc0ver

**Comment by Profitsarts** [comment]
Hi!
Same here since last week. I don't know what did I do but isn't opening again.
I can't inject uncover via impactor as well... Have to do it via tweakbox and I don't know if it's related.
Have you solved it?

**Comment by Matchstic** [comment]
Cannot reproduce this issue over multiple versions of iOS
