### ISSUE TITLE
Can't  install ipas

### ISSUE THREAD

**Issue by rkycyku** [Matchstic/ReProvision#69]
When i try to install ipa from sites like iosddl or wetransfer or if i copy ipa from filza or from files app in ReProvision it says error for ‘(null)’ and when i install the ipa from iosgods or iosninja in safari or chrome and copy to ReProvision it works﻿.

**Comment by igobythisname** [comment]
this issue was closed without resolution or reference? i am having this issue as well, just getting "Error" and "Error, For '(null)':" ?

**Comment by Matchstic** [comment]
It’s closed because I’m not actively maintaining the project. Therefore, won’t be fixing this.

**Comment by igobythisname** [comment]
> It’s closed because I’m not actively maintaining the project. Therefore, won’t be fixing this.

Ok, thanks for the prompt response, Matt!
