### ISSUE TITLE
Can't install ReProvision

### ISSUE THREAD

**Issue by mirceabrb** [Matchstic/ReProvision#70]
I am jailbroken using uncover on iOS 12.0.

While trying to install ReProvision from Cydia i get the error **HTTP/1.1 404 Not Found**

Any idea how to solve this or is it repo related?

Thank you

**Comment by mirceabrb** [comment]
![IMG_6938](https://user-images.githubusercontent.com/49833106/56468483-ca349a00-6435-11e9-991f-90097dc93d99.PNG)

**Comment by Matchstic** [comment]
Fixed; please try again now
