### ISSUE TITLE
ReProvisionning breaks Keynote on IOS 12 due to file association

### ISSUE THREAD

**Issue by thaihugo** [Matchstic/ReProvision#72]
Hi,

There is a bug that disable Keynote on IOS 12.1.1 beta:

If I reprovision any app, or if reprovision does it's backgrond check, Keynote lose its file association.

It means the program cannot load any file. Creating a new file fails too: Keynote does create the file, but it cannot open it as it as lost it's file association to "key" files to ReProvision it seems.

The only way to recover is to delete and reinstall Keynote.

To test the bug:

Install Keynote
Create or open any document (it opens normally)
Close Keynote

reprovision any app
Open keynote
Try to open the previous document
It doesn't open

Can you replicate this problem?

Thanks

**Comment by Matchstic** [comment]
This should now be resolved
