### ISSUE TITLE
ReproVision crashes on my iPad 2

### ISSUE THREAD

**Issue by fichtz** [Matchstic/ReProvision#76]
When I try to re-sign a game called "Cytus 1" from developer Rayark Games its size is 1.4GB. When it reaches 30% the screen turns black and ReProvision closes forcefully.

1-Open ReProvision
2-Tap in Cytus 1
3-Tap on the sign button
4-Wait until it reaches 30%
5-The screen turns black and ReProvision crashes

I hope you can fix the bug so I can successfully sign the application because I don't want to lose my progress again :(

 - iOS 9.3.5
- Device: iPad 2
-Jailbreak with Phoenix Jailbreak
Additional context: I love ReProvision :)

**Comment by Matchstic** [comment]
That application is likely too big to be signed!
