### ISSUE TITLE
Doesn’t accept non-email AppleID

### ISSUE THREAD

**Issue by UA3** [Matchstic/ReProvision#79]
**Describe the bug**
Before iCloud, Apple used to allow the AppleID to be a nickname instead of email, I can use my old nickname as AppleID with Cydia Impactor, but ReProvision won’t accept anything but an email format AppleID. 

Screenshot:
https://i.imgur.com/xrABnGH.jpg
https://i.imgur.com/vlhTO3K.jpg

**Device (please complete the following information):**
 - iOS Version: 12.4
- Device: iPhone 7 Plus

**Comment by Matchstic** [comment]
This is correct behaviour - I wasn’t aware there ever was a nickname feature provided by Apple. Since it’s not advertised now, I won’t be adding support for it.
