### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by k0Iry** [Matchstic/ReProvision#80]
**Describe the bug**
Login with Apple ID used with Impactor just fails.

**To Reproduce**
1. Go to ReProvision
2. Sign in with Apple ID
3. Just prompt "Failure", nothing more

**Screenshots**
![IMG_0169](https://user-images.githubusercontent.com/6511925/63657844-71f11880-c7d8-11e9-9b7b-14b22fb2ff18.png)

**Device (please complete the following information):**
 - iOS Version: 12.4
- Device (iPhone 8 Plus)

**Comment by crazzy007** [comment]
Same problem also

**Comment by iprostatov** [comment]
Same trouble maaan

**Comment by Matchstic** [comment]
I’m currently looking into this. 

@all Does signing in with your Apple ID to https://developer.apple.com fix the issue?

**Comment by k0Iry** [comment]
> I’m currently looking into this. 
> 
> @all Does signing in with your Apple ID to https://developer.apple.com fix the issue?
> 
> > On 26 Aug 2019, at 13:21, iprostatov <notifications@github.com> wrote:
> > 
> > Same trouble maaan
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 

Well, I might not think so since I’ve already signed in this website before, should we do it once more? I’ll do it later :)

**Comment by iprostatov** [comment]
It doesn’t help me man. I was sighed up on this site, but there are the same issue. What should I do with it? Plz help me

**Comment by Matchstic** [comment]
@all Please try this new build: https://www.dropbox.com/s/4sgzdfloeqmfc1n/com.matchstic.reprovision_0.4.3-1_iphoneos-arm.deb?dl=0

It *should* display an error message now from where I think its failing. Please screenshot that error, and post it here.

**Comment by iprostatov** [comment]
![3B4EB138-63DF-4436-9C3D-F78C70B6C1A8](https://user-images.githubusercontent.com/54537851/63707557-41929400-c843-11e9-9c9f-68482a43d0b2.png)

**Comment by Matchstic** [comment]
Another new build, please try this and send screenshot: https://www.dropbox.com/s/iu3x3am7zj0g9ab/com.matchstic.reprovision_0.4.3-2_iphoneos-arm.deb?dl=0

**Comment by k0Iry** [comment]
> Another new build, please try this and send screenshot: https://www.dropbox.com/s/iu3x3am7zj0g9ab/com.matchstic.reprovision_0.4.3-2_iphoneos-arm.deb?dl=0
> On 26 Aug 2019, 17:51 +0100, iprostatov <notifications@github.com>, wrote:
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 


The internet connection appears to be offline.

**Comment by Matchstic** [comment]
Hmm... what country are you in?

**Comment by k0Iry** [comment]
> Hmm... what country are you in?

China with or without proxy network :(

**Comment by Matchstic** [comment]
That’s probably why! There is another issue somewhere that has instructions on how to fix this.

**Comment by iprostatov** [comment]
I’m based in Russia. Why do I have this problem? :cccc

**Comment by DeafEyeJedi** [comment]
Interesting. I haven't seen this phenomenon on my end. Running both iPhone XR and iPad mini 5 on 12.2 with no issues. Is this related to iOS 12.4?
    On Tuesday, August 27, 2019, 3:00:53 PM PDT, iprostatov <notifications@github.com> wrote:  
 
 
I’m based in Russia. Why do I have this problem? :cccc

**Comment by Matchstic** [comment]
@all New build: https://www.dropbox.com/s/xuvfwahjl9emcv3/com.matchstic.reprovision_0.4.3-4_iphoneos-arm.deb?dl=0

Changes:
- Added new entitlements that should ensure devices from China request for network access
- Added extra check for if 2FA login is required.

PLEASE PLEASE PLEASE let me know if this works, or doesn't work. For Chinese devices, there's a little extra code that I can add too.

**Comment by lpawluk** [comment]
How do you install it

**Comment by Matchstic** [comment]
You can  open it with Filza, which then does everything else for you.

**Comment by lpawluk** [comment]
Now it makes it through the first Id but not the second

**Comment by Matchstic** [comment]
@lpawluk what error do you get?

**Comment by lpawluk** [comment]
Just failure

**Comment by lpawluk** [comment]
Here is the second screen

**Comment by k0Iry** [comment]
> @lpawluk what error do you get?

Still offline error...

**Comment by lpawluk** [comment]
No error message just failure

**Comment by IhateSignUps1** [comment]
having this issue is in the Us

**Comment by lpawluk** [comment]
Yes it is

**Comment by Matchstic** [comment]
@ALL new build again: https://www.dropbox.com/s/kcp68knh8x5nkkd/com.matchstic.reprovision_0.4.3-5_iphoneos-arm.deb?dl=0

This adds extra code I think is required to get past the new 'Internet connection appears to be offline' error on Chinese devices. Please let me know if this works or not.

 It DOES NOT include fixes for anything else login related.

**Comment by k0Iry** [comment]
> @ALL new build again: https://www.dropbox.com/s/kcp68knh8x5nkkd/com.matchstic.reprovision_0.4.3-5_iphoneos-arm.deb?dl=0
> 
> This adds extra code I think is required to get past the new 'Internet connection appears to be offline' error on Chinese devices. Please let me know if this works or not.
> 
>  It DOES NOT include fixes for anything else login related.

Thx, it works!

**Comment by xxSkyy** [comment]
Could someone please reupload this build ? I've got same problem

**Comment by DeafEyeJedi** [comment]
This is what I'm seeing when logging out and try to log back in...
    On Wednesday, January 15, 2020, 04:29:37 PM PST, Sky <notifications@github.com> wrote:  
 
 
Could someone please reupload this build ? I've got same problem

**Comment by DeafEyeJedi** [comment]
This is happening when I try to log back into ReProvision via Apple ID (regular passowrd since the app-specfic passwords are no longer supported) so what gives? 
    On Wednesday, January 15, 2020, 04:29:37 PM PST, Sky <notifications@github.com> wrote:  
 
 
Could someone please reupload this build ? I've got same problem
