### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Banana-Jordan** [Matchstic/ReProvision#83]
Can’t login with ReProvision, is it because I jailbroke my iPhone 12.4 with Unc0ver, not Cydia Impactor?

![3A77B391-F006-4CAC-B7C3-71FFE3248BED](https://user-images.githubusercontent.com/54600809/63803958-63108000-c916-11e9-986b-0a8a204a3861.jpeg)

I’m using an iPhone SE 128 GB, iOS 12.4, jailbroke with Unc0ver

**Comment by Matchstic** [comment]
Just follow the onscreen instructions!

**Comment by Banana-Jordan** [comment]
Oh sorry, I misread the Failure instruction, I’m dumb. Sorry I wasted your time and thanks for the patience! :)
