### ISSUE TITLE
Cannot open ReProvision on my iPad 

### ISSUE THREAD

**Issue by downyjack** [Matchstic/ReProvision#86]
**Describe the bug**
Unable to open ReProvision on my iPad iOS 12.1.1, uncover 3.5.6

Here is the crash log
Date: 2019-08-29 02:30:10 +0000
Process: ReProvision
Bundle id: com.matchstic.reprovision.ios
Exception type: NSInvalidArgumentException
Reason: data parameter is nil
Culprit: Unknown
Device: iPad (5th generation), iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001b2ba0edc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001b1d71a40 objc_exception_throw
2   CoreFoundation                      0x00000001b2aa7594 -[NSCache init]
3   Foundation                          0x00000001b3527490 +[NSPropertyListSerialization propertyListWithData:options:format:error:]
4   ReProvision                         0x0000000100a4abf0 -[RPVApplication -[RPVApplication _provisioningProfileAtPath:]
5   ReProvision                         0x0000000100a4a7e0 -[RPVApplication -[RPVApplication applicationExpiryDate]
6   ReProvision                         0x0000000100a74224 -[RPVApplicationDatabase -[RPVApplicationDatabase getApplicationsWithExpiryDateBefore:andAfter:date:forTeamID:]
7   ReProvision                         0x0000000100a624b0 -[RPVInstalledViewController -[RPVInstalledViewController _reloadDataSources]
8   ReProvision                         0x0000000100a605d4 -[RPVInstalledViewController -[RPVInstalledViewController viewDidLoad]
9   UIKitCore                           0x00000001df4e7fc8 -[UIViewController loadViewIfRequired]
10  UIKitCore                           0x00000001df4e83f8 -[UIViewController view]
11  ReProvision                         0x0000000100a367bc -[RPVSplitViewDetailViewController -[RPVSplitViewDetailViewController presentSelectedItem:]
12  ReProvision                         0x0000000100a40bdc -[RPVRootViewController -[RPVRootViewController _setupSplitController:]
13  ReProvision                         0x0000000100a40a5c -[RPVRootViewController -[RPVRootViewController viewDidLoad]
14  UIKitCore                           0x00000001df4e7fc8 -[UIViewController loadViewIfRequired]
15  UIKitCore                           0x00000001df4e83f8 -[UIViewController view]
16  UIKitCore                           0x00000001dfae69e8 -[UIWindow addRootViewControllerViewIfPossible]
17  UIKitCore                           0x00000001dfae6f90 -[UIWindow _setHidden:forced:]
18  UIKitCore                           0x00000001dfaf7f98 -[UIWindow makeKeyAndVisible]
19  UIKitCore                           0x00000001dfaa7d78 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
20  UIKitCore                           0x00000001dfaad714 -[UIApplication _runWithMainScene:transitionContext:completion:]
21  UIKitCore                           0x00000001df349074 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke
22  UIKitCore                           0x00000001df351cf4 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:]
23  UIKitCore                           0x00000001df348cf0 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]
24  UIKitCore                           0x00000001df349690 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:]
25  UIKitCore                           0x00000001df347790 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke
26  UIKitCore                           0x00000001df34743c -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]
27  UIKitCore                           0x00000001df34c5fc __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke
28  UIKitCore                           0x00000001df34d55c _performActionsWithDelayForTransitionContext
29  UIKitCore                           0x00000001df34c4b4 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]
30  UIKitCore                           0x00000001df3513a0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:]
31  UIKitCore                           0x00000001dfaabc0c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
32  UIKitCore                           0x00000001df69697c -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
33  FrontBoardServices                  0x00000001b55d79d4 -[FBSSceneImpl _didCreateWithTransitionContext:completion:]
34  FrontBoardServices                  0x00000001b55e279c __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2
35  FrontBoardServices                  0x00000001b55e1e94 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke
36  libdispatch.dylib                   0x00000001b25da484 _dispatch_client_callout
37  libdispatch.dylib                   0x00000001b257de10 _dispatch_block_invoke_direct$VARIANT$mp
38  FrontBoardServices                  0x00000001b5616a9c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
39  FrontBoardServices                  0x00000001b5616728 -[FBSSerialQueue _performNext]
40  FrontBoardServices                  0x00000001b5616d44 -[FBSSerialQueue _performNextFromRunLoopSource]
41  CoreFoundation                      0x00000001b2b311f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
42  CoreFoundation                      0x00000001b2b31170 __CFRunLoopDoSource0
43  CoreFoundation                      0x00000001b2b30a54 __CFRunLoopDoSources0
44  CoreFoundation                      0x00000001b2b2b920 __CFRunLoopRun
45  CoreFoundation                      0x00000001b2b2b1f0 CFRunLoopRunSpecific
46  GraphicsServices                    0x00000001b4da4584 GSEventRunModal
47  UIKitCore                           0x00000001dfaaf4c0 UIApplicationMain
48  ReProvision                         0x0000000100a537cc main
49  libdyld.dylib                       0x00000001b25eabb4 start

**Comment by Kyogre** [comment]
same here (ipad 2017, ios 10.3.3, doublehelix). Used Reprovision 0.3.2 for 1.5 years, but today when I tried to open Reprovision it just crashed. Tried to delete all the files associated with reprovision with Filza and install latest Reprovision 0.4.2 - no luck.

**Comment by Matchstic** [comment]
Hey @ALL, please try this new build: https://www.dropbox.com/s/kcp68knh8x5nkkd/com.matchstic.reprovision_0.4.3-5_iphoneos-arm.deb?dl=0

**Comment by Kyogre** [comment]
@Matchstic, tried 0.4.3-5 - it still crashes

**Comment by ygzok** [comment]
0.4.3-5 crashes.

**Comment by fichtz** [comment]
Cannot open the app :(

**Comment by ygzok** [comment]
After two days the app was able to open again, resigned an app, crashes again with the same report.

**Comment by Matchstic** [comment]
@ALL Please try this build and let me know how it goes: https://www.dropbox.com/s/79w065gdn5ked0m/com.matchstic.reprovision_0.4.3-7_iphoneos-arm.deb?dl=0

**Comment by fichtz** [comment]
It's working, thanks you :D

**Comment by ygzok** [comment]
Works fully with 0.4.3-7, thanks.

**Comment by Matchstic** [comment]
Version 0.4.4 is now available which fixes this publicly
