### ISSUE TITLE
ReProvision crash at launch after resigned chimera

### ISSUE THREAD

**Issue by StigiTT** [Matchstic/ReProvision#87]
**Describe the bug**

I resigned chimera and ReProvision crash and after this he won’t to launch
1. Go to ReProvision 
2. Tap on chimera
3. Resigne it and app crash (for me)

 - iOS 12.4
- IPhone 

Logs:
Date: 2019-08-30 19:02:35 +0000
Process: ReProvision
Bundle id: com.matchstic.reprovision.ios
Exception type: NSInvalidArgumentException
Reason: data parameter is nil
Culprit: Unknown
Device: iPhone 8, iOS 12.4
Call stack:
0   CoreFoundation                      0x000000021e4d29a4 __exceptionPreprocess
1   libobjc.A.dylib                     0x000000021d6ab9f8 objc_exception_throw
2   CoreFoundation                      0x000000021e3dcbc0 -[NSCache init]
3   Foundation                          0x000000021ee32de0 +[NSPropertyListSerialization propertyListWithData:options:format:error:]
4   ReProvision                         0x0000000102fa2bf0 -[RPVApplication -[RPVApplication _provisioningProfileAtPath:]
5   ReProvision                         0x0000000102fa27e0 -[RPVApplication -[RPVApplication applicationExpiryDate]
6   ReProvision                         0x0000000102fcc224 -[RPVApplicationDatabase -[RPVApplicationDatabase getApplicationsWithExpiryDateBefore:andAfter:date:forTeamID:]
7   ReProvision                         0x0000000102fba4b0 -[RPVInstalledViewController -[RPVInstalledViewController _reloadDataSources]
8   ReProvision                         0x0000000102fb85d4 -[RPVInstalledViewController -[RPVInstalledViewController viewDidLoad]
9   UIKitCore                           0x000000024a980224 -[UIViewController loadViewIfRequired]
10  UIKitCore                           0x000000024a980628 -[UIViewController view]
11  UIKitCore                           0x000000024a8c57f4 -[UITabBarController transitionFromViewController:toViewController:transition:shouldSetSelected:]
12  UIKitCore                           0x000000024a8c4bf0 -[UITabBarController transitionFromViewController:toViewController:]
13  UIKitCore                           0x000000024a8c1510 -[UITabBarController _setSelectedViewController:]
14  UIKitCore                           0x000000024a8c12e0 -[UITabBarController setSelectedViewController:]
15  UIKitCore                           0x000000024b3b38f0 +[UIView(Animation) performWithoutAnimation:]
16  UIKitCore                           0x000000024a8bb870 -[UITabBarController _selectDefaultViewControllerIfNecessaryWithAppearanceTransitions:]
17  UIKitCore                           0x000000024a8bc6c0 -[UITabBarController viewWillAppear:]
18  UIKitCore                           0x000000024a985940 -[UIViewController _setViewAppearState:isAnimating:]
19  UIKitCore                           0x000000024a985e34 __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke
20  CoreFoundation                      0x000000021e3bba7c -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:]
21  UIKitCore                           0x000000024a985bc4 -[UIViewController _setViewAppearState:isAnimating:]
22  UIKitCore                           0x000000024a98600c -[UIViewController __viewWillAppear:]
23  UIKitCore                           0x000000024a987698 -[UIViewController viewWillMoveToWindow:]
24  UIKitCore                           0x000000024b3aab4c -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:]
25  UIKitCore                           0x000000024b3babd4 -[UIView(Internal) _addSubview:positioned:relativeTo:]
26  UIKitCore                           0x000000024af5eff0 -[UIWindow addRootViewControllerViewIfPossible]
27  UIKitCore                           0x000000024af5f40c -[UIWindow _setHidden:forced:]
28  UIKitCore                           0x000000024af6fce8 -[UIWindow makeKeyAndVisible]
29  UIKitCore                           0x000000024af22908 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
30  UIKitCore                           0x000000024af27fe0 -[UIApplication _runWithMainScene:transitionContext:completion:]
31  UIKitCore                           0x000000024a7eb2a4 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke
32  UIKitCore                           0x000000024a7f383c +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:]
33  UIKitCore                           0x000000024a7eaf28 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]
34  UIKitCore                           0x000000024a7eb818 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:]
35  UIKitCore                           0x000000024a7e9b64 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke
36  UIKitCore                           0x000000024a7e982c -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]
37  UIKitCore                           0x000000024a7ee36c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke
38  UIKitCore                           0x000000024a7ef150 _performActionsWithDelayForTransitionContext
39  UIKitCore                           0x000000024a7ee224 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]
40  UIKitCore                           0x000000024a7f2f24 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:]
41  UIKitCore                           0x000000024af265e8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
42  UIKitCore                           0x000000024ab22e04 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
43  FrontBoardServices                  0x0000000220e4e9fc -[FBSSceneImpl _didCreateWithTransitionContext:completion:]
44  FrontBoardServices                  0x0000000220e5840c __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2
45  FrontBoardServices                  0x0000000220e57c14 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke
46  libdispatch.dylib                   0x000000021df117d4 _dispatch_client_callout
47  libdispatch.dylib                   0x000000021dee91ec _dispatch_block_invoke_direct$VARIANT$armv81
48  FrontBoardServices                  0x0000000220e89040 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
49  FrontBoardServices                  0x0000000220e88cdc -[FBSSerialQueue _performNext]
50  FrontBoardServices                  0x0000000220e89294 -[FBSSerialQueue _performNextFromRunLoopSource]
51  CoreFoundation                      0x000000021e464728 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
52  CoreFoundation                      0x000000021e4646a8 __CFRunLoopDoSource0
53  CoreFoundation                      0x000000021e463f90 __CFRunLoopDoSources0
54  CoreFoundation                      0x000000021e45eecc __CFRunLoopRun
55  CoreFoundation                      0x000000021e45e7c0 CFRunLoopRunSpecific
56  GraphicsServices                    0x000000022065f79c GSEventRunModal
57  UIKitCore                           0x000000024af29c38 UIApplicationMain
58  ReProvision                         0x0000000102fab7cc main
59  libdyld.dylib                       0x000000021df228e0 start

**Comment by thies226j** [comment]
for me it is the same, but I am using u0.

**Comment by StigiTT** [comment]
Yeah bug is with chimera or unc0ver

**Comment by thorkavi** [comment]
But can you reinstall ReProvision? Because i can’t install again

**Comment by StigiTT** [comment]
No I cant reinstall

**Comment by thies226j** [comment]
I can reinstall it after removing it, running iCleaner and rejailbreaking

**Comment by thorkavi** [comment]
I follow your steps, but i can’t reinstall @thies226j

**Comment by StigiTT** [comment]
Does not actually work I reinstalled and in Cydia because I went to unc0ver when I install it I don't even press on restart the springboard that Cr4shed tells me that ReProvision to crash

**Comment by thies226j** [comment]
ok that's weird, now I cannot get it to run again either. Now it just crashes after opening. even after reinstalling it in Cydia.

**Comment by StigiTT** [comment]
It’s big bug

**Comment by Matchstic** [comment]
@ALL Please try this build and let me know how it goes: https://www.dropbox.com/s/79w065gdn5ked0m/com.matchstic.reprovision_0.4.3-7_iphoneos-arm.deb?dl=0

**Comment by thorkavi** [comment]
@Matchstic Install this version and work perfect for my. Thank you

**Comment by StigiTT** [comment]
I will test

**Comment by StigiTT** [comment]
Work perfectly 👌

**Comment by StigiTT** [comment]
I will close this thread
