### ISSUE TITLE
Support for 2 byte characters

### ISSUE THREAD

**Issue by sohsatoh** [Matchstic/ReProvision#89]
**Describe the bug**
If my Apple ID or teamName in embedded.mobileprovision has 2-byte characters, ReProvision will be crashed.

**To Reproduce**
1. Set your name as something like "日本" on Apple ID.
2. Login with the account

or

1. Install IPA with your account
2. Modify teamName in embedded.mobileprovision as 2-byte characters
3. Open ReProvision

**Device (please complete the following information):**
 - iOS Version: iOS 12.4
- Device: iPhone X

**Comment by Matchstic** [comment]
Known issue, but that thanks for opening the issue - I’m working on it when I can!

**Comment by Matchstic** [comment]
Please try this build and let me know how it goes: https://www.dropbox.com/s/79w065gdn5ked0m/com.matchstic.reprovision_0.4.3-7_iphoneos-arm.deb?dl=0

**Comment by Luck-muss** [comment]
I'm from #90 issue, tried 0.4.3-7 and it worked, thank you!

**Comment by Matchstic** [comment]
Version 0.4.4 is now available which fixes this publicly
