### ISSUE TITLE
Unable to sign on a device migrated from others 

### ISSUE THREAD

**Issue by qwqVictor** [Matchstic/ReProvision#94]
Hi.
I migrated my data from a jailbroken iPhone SE to a new iPhone 8. They’re both running iOS 12.4. 
I’ve found that ReProvision can’t sign unc0ver anymore. When it has gone over the 30% progress, it suddenly go to 100% but the app won’t be signed and installed.
I thought its configuration might be broken. But I have no idea how to delete the configuration of ReProvision. `apt purge` doesn’t work.
Looking forward to the solution.

**Comment by qwqVictor** [comment]
I have solved this problem by finding all files whose names contains `reprovision`.
So please add a feature to clear all configurations inside the app.

**Comment by Matchstic** [comment]
Logging out and then logging in again to ReProvision should also have solved your issue.

**Comment by badger200** [comment]
> I have solved this problem by finding all files whose names contains `reprovision`.

Sorry this might be offtopic but what did you use to find all files?

I always use findutils “locate” (of course, after doing an initial “updatedb”) But was curious if there’s a better way, real-time. Findutils-locate is instant, but filename data as stale as the last time updatedb was performed.

**Comment by qwqVictor** [comment]
> > I have solved this problem by finding all files whose names contains `reprovision`.
> 
> Sorry this might be offtopic but what did you use to find all files?
> 
> I always use findutils “locate” (of course, after doing an initial “updatedb”) But was curious if there’s a better way, real-time. Findutils-locate is instant, but filename data as stale as the last time updatedb was performed.

I did this with Filza
