### ISSUE TITLE
submitDevelopmentCSR: Please update to Xcode 7.3 or later to continue developing with your Apple ID.

### ISSUE THREAD

**Issue by xMarkSt** [Matchstic/ReProvision#96]
**Describe the bug**
I cannot sign the IPA for h3lix jailbreak. When at 30%, it gives the following error message:
submitDevelopmentCSR: Please update to Xcode 7.3 or later to continue developing with your Apple ID.
I don't know if this also happens with other apps. 

**To Reproduce**
1. Try to resign an installed application, in my case h3lix jailbreak.
2. The error message appears in the notification bar.

**Expected behavior**
The app to be resigned.

**Screenshots**
![IMG_0180](https://user-images.githubusercontent.com/5182115/68333287-873bca80-00d8-11ea-88dc-985bdf51a5ab.PNG)

**Device (please complete the following information):**
 - iOS 10.3.3
 - iPad 4

**Comment by Matchstic** [comment]
Thanks, I’ll use this ticket as the one to post progress updates on. Just found out about it myself!

First instinct is to update the values hard coded here:  https://github.com/Matchstic/ReProvision/blob/1dc76d61361bd30c716e848e73bf9a3d7c35fde2/Shared/libProvision/Apple%20Services/EEAppleServices.m#L60

**Comment by rileytestut** [comment]
I'm looking into this myself for AltStore. It seems that there are three new headers that need to be included when making requests to Apple: `X-Apple-GS-Token`,` DSESSIONID`, and `X-Mme-Device-Id`. I'm still researching, but there's more info here: https://github.com/rileytestut/AltStore/issues/57

**Comment by Matchstic** [comment]
That’s a huge help, I’ll keep an eye on your progress!

**Comment by Matchstic** [comment]
Had a chance to do some digging of my own just now. It appears that the sign in process on idmsa.apple.com via clientDaw.cgi gives a “JSESSIONID” back in the “Set-Cookie” response header. Might be relevant to check into Xcode’s user sign in process for the remaining two header fields.

**Comment by kabiroberai** [comment]
I've been looking into this myself for Supercharge, and I made a few discoveries which I'd like to share here in the interest of figuring this out quickly (spoiler alert: if we want future-proofing, those three headers aren't enough).

1. Xcode seems to do most of the header-related magic in DVTFoundation.framework. To get all of the new headers, run `[[[DVTDeveloperAccountCredentialsManager defaultAccountCredentialsManager] accountCredentialsForUsername:@"EMAIL_ID_HERE" error:nil] authenticationHeaders]` while attached to the Xcode process

2. The `authenticationHeaders` method appears to use two sources. Firstly, some headers are "manually provided" (`-[DVTDeveloperAccountCredentials _manuallyProvidedAuthenticationHeaders]`):
- `X-Apple-App-Info`: always `"com.apple.gs.xcode.auth"`
- `X-MMe-Client-Info`: `[[AKDevice currentDevice] serverFriendlyDescription]` (AK = AuthKit)
- `X-Mme-Device-Id`: [[AKDevice currentDevice] uniqueDeviceIdentifier]
- `X-Apple-GS-Token`: `-[DVTDeveloperAccountCredentials URLCredential].password`. Note that this is not a "password" in the traditional sense, however it _does_ represent a single developer account. I assume this is set while logging in, as it's stored in the keychain thereafter
- `X-Apple-I-Identity-Id`: `URLCredential.username` (refer to GS-Token)

3. The other source is AuthKit's headers (`[[[AKAppleIDSession alloc] initWithIdentifier:@"com.apple.gs.xcode.auth"] appleIDHeadersForRequest:nil]`)
- `X-Apple-I-Client-Time`, `X-Apple-I-Locale`, `X-Apple-I-TimeZone`: self-explanatory
- `X-Apple-I-MD[-*]`: these headers appear to be related to Anisette ([more info](https://blog.elcomsoft.com/2017/11/icloud-authentication-tokens-inside-out/)), which replaces `myacinfo`. Also this means we shouldn't be using `clientDaw.cgi` anymore – in fact I already have a working 2FA login system in Supercharge but that may have to go too, considering the whole AuthKit thing.

4. It's possible to copy _most_ of this data from an existing request and reuse it. However, `X-Apple-I-MD` represents a one time password which changes between sessions, so updating that might be a little tricky (and once we know how to do that, it's worth updating the other headers too).

5. Re [this](https://github.com/rileytestut/AltStore/issues/57#issuecomment-550582122), `DSESSIONID` definitely seems like it's being reused after the first request of the session. I feel like it might've been failing because of the one-time-password thing I mentioned.

6. A little speculation: based on the fact that the new API requires `X-Mme-Device-Id` and Anisette data, it seems like it'll be really easy to fingerprint devices. Apple could fully well begin banning/restricting devices that don't strictly adhere to the request format (since they'll know they're from a third-party app then), so we should ensure that the request is indistinguishable from a first-party one. Also, with reference to point 4, this means hardcoding the device ID and Anisette data is a bad idea because Apple can very easily ban that single device ID.

All in all, any solution to this will probably have to involve entirely reverse-engineering AuthKit, or coming up with a super creative workaround

**Comment by mrkiko** [comment]
thank you for your work guys!

**Comment by rileytestut** [comment]
Awesome, thanks so much for this @kabiroberai! I'll move my own progress updates here then to consolidate everything in once place.

Clarifying my `DSESSIONID` note from the other thread, I noticed that the `listTeams` endpoint still works as before without any of these changes, and also returns a `DSESSIONID` value in the response headers. It doesn't seem like _this_ value can be used for later requests, but any `DSESSIONID` sniffed from Xcode works fine for multiple requests.

As for creative workarounds, do we know if iCloud on Windows uses this new auth flow for anything? 🤔

**Comment by aovestdipaperino** [comment]
> do we know if iCloud on Windows uses this new auth flow for anything

I would imagine that the new authentication code requires a chain of trust that ends with Apple's certificate.

**Comment by ARay1219** [comment]
I’m having this exact same issue on an iPhone X running 12.4 with Chimera.

**Comment by TrungNguyen1909** [comment]
Got it working, Could now generate `X-Apple-I-MD[-*]` for any requests. You will need those headers for most of the requests.

```objc
#import <Foundation/Foundation.h>
@interface AKAppleIDSession : NSObject
- (id)_pairedDeviceAnisetteController;
- (id)_nativeAnisetteController;
- (void)_handleURLResponse:(id)arg1 forRequest:(id)arg2 withCompletion:(id)arg3;
- (void)_generateAppleIDHeadersForSessionTask:(id)arg1 withCompletion:(id)arg2;
- (id)_generateAppleIDHeadersForRequest:(id)arg1 error:(id *)arg2;
- (id)_genericAppleIDHeadersDictionaryForRequest:(id)arg1;
- (void)handleResponse:(id)arg1 forRequest:(id)arg2 shouldRetry:(char *)arg3;
- (id)appleIDHeadersForRequest:(id)arg1;
- (void)URLSession:(id)arg1 task:(id)arg2 getAppleIDHeadersForResponse:(id)arg3 completionHandler:(id)arg4;
- (id)relevantHTTPStatusCodes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithIdentifier:(id)arg1;
- (id)init;

@end
int main(int argc, char *argv[]) {
    @autoreleasepool {
        NSMutableURLRequest* req = [[NSMutableURLRequest alloc] initWithURL:[[NSURL alloc] initWithString:@"https://developerservices2.apple.com/services/QH65B2/listTeams.action?clientId=XABBG36SBA"]];
        [req setHTTPMethod:@"POST"];
        
        AKAppleIDSession* session = [[AKAppleIDSession alloc] initWithIdentifier:@"com.apple.gs.xcode.auth"];
        NSMutableURLRequest* nreq = [session appleIDHeadersForRequest:req];
        NSLog(@"%@",nreq);
    }
}
```
This code will copy `req` and append the required headers in the `nreq`. You will need to link AuthKit, put `com.apple.authkit.client.private` in the entitlement. To test on macOS, you may need to [patch AMFID](https://pvieito.com/2016/12/amfid-patching).

Bellow is my code for amfid on macOS 18G103(10.14.6)
```c
#include <Security/Authorization.h>
#include <errno.h>
#include <mach/mach.h>
#include <mach/mach_vm.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/ptrace.h>
#include <sys/types.h>
#include <unistd.h>
int acquireTaskportRight() {
  OSStatus stat;
  AuthorizationItem taskport_item[] = {{"system.privilege.taskport:"}};
  AuthorizationRights rights = {1, taskport_item}, *out_rights = NULL;
  AuthorizationRef author;
  int retval = 0;

  AuthorizationFlags auth_flags =
      kAuthorizationFlagExtendRights | kAuthorizationFlagPreAuthorize |
      kAuthorizationFlagInteractionAllowed | (1 << 5);

  stat = AuthorizationCreate(NULL, kAuthorizationEmptyEnvironment, auth_flags,
                             &author);
  if (stat != errAuthorizationSuccess) {
    return 0;
  }

  stat = AuthorizationCopyRights(
      author, &rights, kAuthorizationEmptyEnvironment, auth_flags, &out_rights);
  if (stat != errAuthorizationSuccess) {
    printf("fail");
    return 1;
  }
  return 0;
}

void check(int cond, char *msg) {
  if (!cond) {
    printf("%s\n", msg);
    exit(-1);
  }
}
int main(int argc, char *argv[]) {
  int infoPid;
  kern_return_t kret;
  mach_port_t task;
  thread_act_port_array_t threadList;
  mach_msg_type_number_t threadCount;
  x86_thread_state64_t state;
  if (argc < 2) {
    kret = pid_for_task(mach_task_self(), &infoPid);
    if (kret != KERN_SUCCESS) {
      mach_error("pid_for_task():", kret);
      exit(0);
    }
  } else
    infoPid = atoi(argv[1]);
  if (acquireTaskportRight() != 0) {
    printf("acquireTaskportRight() failed!\n");
    exit(0);
  }

  kret = task_for_pid(mach_task_self(), infoPid, &task);
  if (kret != KERN_SUCCESS) {
    printf("task_for_pid() failed with message %s!\n", mach_error_string(kret));
    exit(0);
  }
  kern_return_t err;
  mach_msg_type_number_t region_count = VM_REGION_BASIC_INFO_COUNT_64;
  memory_object_name_t object_name = MACH_PORT_NULL; /* unused */
  mach_vm_size_t target_first_size = 0x1000;
  mach_vm_address_t target_first_addr = 0x0;
  struct vm_region_basic_info_64 region = {0};
  printf("[+] About to call mach_vm_region\n");
  err = mach_vm_region(task, &target_first_addr, &target_first_size,
                       VM_REGION_BASIC_INFO_64, (vm_region_info_t)&region,
                       &region_count, &object_name);

  if (err != KERN_SUCCESS) {
    printf("[-] Failed to get the region: %s\n", mach_error_string(err));
    return -1;
  }
  printf("[+] Got base address\n");
  uint64_t base = target_first_addr;
  printf("binary load address: 0x%llx\n", base);
  task_suspend(task);
  vm_offset_t buf;
  unsigned int dataCnt = 8;
  kret = vm_read(task, base, 8, &buf, &dataCnt);
  //  assert(*(int64_t*)buf==0x1000007feedfacf);
  char patched[0x4] = {0x31,0xc0,0x29,0xdb};
  kret = vm_protect(task, base, target_first_size, 0, VM_PROT_ALL);
  printf("%s\n", mach_error_string(kret));
  kret = vm_write(task, base + 0x3294, (pointer_t)patched, 0x4);
  printf("%s\n", mach_error_string(kret));
  task_resume(task);
  return 0;
}
```

**Comment by kabiroberai** [comment]
@TrungNguyen1909 for what it's worth, you can also disable amfid by setting `amfi_get_out_of_my_way=0x1` in your boot args. Either way though, imo it's an _extremely_ bad idea to disable amfi on macOS because it exposes the user's computer to a ton of vulnerabilities. As for iOS, while jailbreaks allow the use of private entitlements, Apple can probably detect which OS the AuthKit token was generated from, so it's possible for them to whitelist just macOS. All in all what I'm saying is it's a way better idea to RE AuthKit's requests. Maybe using AuthKit in your own process can make it easier to reverse-engineer it, but unfortunately the actual requests are made using the AuthKit daemon `akd`

**Comment by DeafEyeJedi** [comment]
I think our best bet would be to wait for an official update from Matchstic himself? I don’t mind using the Cydia Impactor every 7 days within a laptop for the time being until this gets resolved.

**Comment by kabiroberai** [comment]
@DeafEyeJedi not at all – we really appreciate input from the community, and in fact Riley, Matt, and I are all working together to fix this. This error entails an entire rewrite of the authentication mechanism to simulate AuthKit, which hasn’t ever been done before (at least publicly). Cydia Impactor is also currently broken for the same reason.

**Comment by aovestdipaperino** [comment]
Is there a different channel where things are discussed?

**Comment by TrungNguyen1909** [comment]
@kabiroberai , The host machine's information(MLB,ROM, hardware model,os) gathering is happening in the AuthKit framework of the local process, not on the `akd` daemon.
Errr, I dunno but this function in the `akd` daemon is interesting `+[AKADIProxy requestOTPForDSID:0xfffffffffffffffe outMID:outMIDSize:outOTP:outOTPSize:]` but something is wrong when I try to generate the pseudo code in IDA. Can someone give it a look?

**Comment by kaich** [comment]
@TrungNguyen1909  Do you have solve it ? Do you have any demo?

**Comment by TrungNguyen1909** [comment]
> X-Apple-GS-Token: -[DVTDeveloperAccountCredentials URLCredential].password. Note that this is not a "password" in the traditional sense, however it does represent a single developer account. I assume this is set while logging in, as it's stored in the keychain thereafter
> X-Apple-I-Identity-Id: URLCredential.username (refer to GS-Token)

You need `AKAppleIDAuthenticationController`(AuthKit) to get those.


No, I don't have any demo tbh. Although I can still sideload apps from my Mac to my iPhone using Xcode(create a project with a bundle ID,...etc) & iOS App Signer, It's still impractical because reliance on AuthKit makes sideloading from Windows sounds impossible

**Comment by ashleyjcharman** [comment]
![9DF90A71-99DD-47F7-91D6-62B29D1F80FF](https://user-images.githubusercontent.com/55964015/68533318-f0148400-031e-11ea-9fd5-595021f12f7f.jpeg)
I’m not a developer, but I recieved this message today regarding ReProvision. I was wandering if it was of any use to any of you, if not no worries :)

**Comment by esterTion** [comment]
Appreciate all the research and work you guys do. 
So... I suggest while the research goes on, could we have a temporary working version released? 🤔
Mine Is 1 day away from expiring, and I believe many are in same situation. 
(Not to mention unc0ver causes kernel panic almost once a day)

Maybe have some hardcoded headers is good enough?
If you guys want to perfect it before release, I can totally understand that. 😄

**Comment by TrungNguyen1909** [comment]
```
{
    AKAltDSID = "REDACTED";
    AKAuthenticationMode = 1;
    AKDSID = REDACTED;
    AKIDMSToken =     {
        "com.apple.gs.appleid.auth" = "REDACTED BASE64 String";
        "com.apple.gs.authagent.auth" = "REDACTED BASE64 String";
        "com.apple.gs.beta.auth" = "REDACTED BASE64 String";
        "com.apple.gs.dip.auth" = "REDACTED BASE64 String";
        "com.apple.gs.global.auth" = "REDACTED BASE64 String";
        "com.apple.gs.icloud.auth" = "REDACTED BASE64 String";
        "com.apple.gs.icloud.family.auth" = "REDACTED BASE64 String";
        "com.apple.gs.icloud.storage.buy" = "REDACTED BASE64 String";
        "com.apple.gs.idms.hb" = "REDACTED BASE64 String";
        "com.apple.gs.idms.ln" = "REDACTED BASE64 String";
        "com.apple.gs.idms.pet" = "REDACTED BASE64 String";
        "com.apple.gs.itunes.mu.invite" = "REDACTED BASE64 String";
        "com.apple.gs.news.auth" = "REDACTED BASE64 String";
        "com.apple.gs.pb.auth" = "REDACTED BASE64 String";
        "com.apple.gs.supportapp.auth" = "REDACTED BASE64 String";
        "com.apple.gs.xcode.auth" = "REDACTED BASE64 String";
    };
    AKPassword = "REDACTED BASE64 String";
    AKSecurityLevel = 2;
    AKUsername = "REDACTED email";
}
```
Anything else? guys?

**Comment by TrungNguyen1909** [comment]
Recently authenticated, could now fetch teams, certificates. working in AltSign project. @rileytestut , could you send me the snippets/API calls to (re)sign an application with AltSign please? Thanks

**Comment by mrkiko** [comment]
On Sat, 9 Nov 2019, esterTion wrote:
...
> (Not to mention unc0ver causes kernel panic almost once a day)

Is this a known issue? Currently should be running something like 3.7.0~b1 with no stability issues, even tough the device slows down a little bit but I am convinced it's not related to unc0ver itself.

**Comment by esterTion** [comment]
> Is this a known issue? Currently should be running something like 3.7.0~b1 with no stability issues, even tough the device slows down a little bit but I am convinced it's not related to unc0ver itself.

Well, my phone always just freeze to death, or the substrate simply stoped working, neither did MTerminal. ( tweak not injecting and terminal with [Killed 9] )
I feel like kernel is messed up somehow, but not sure where.

**Comment by mrkiko** [comment]
On Sun, 10 Nov 2019, esterTion wrote:
> Well, my phone always just freeze to death, or the substrate simply stoped working, neither did MTerminal. ( tweak not injecting and terminal with [Killed 9] )
> I feel like kernel is messed up somehow, but not sure where.
> 
Hope you can solve your problem; maybe a bad extension is active? Does using Safe Mode help in this respect?

**Comment by esterTion** [comment]
Well, when it dies there’s nothing to rescue. 
I feel all my installed tweak are functioning, and try hunting is hard. 
You never know if there’s nothing wrong, only if there’s something wrong. 

( also this seems out of topic in this issue🤔)

**Comment by TrungNguyen1909** [comment]
Fixed, Got ReProvision working. Still need some cleanup, PR soon...

**Comment by Matchstic** [comment]
> Fixed, Got ReProvision working. Still need some cleanup, PR soon...

Very much appreciated! I do want to refactor EEAppleServices for setting headers on a request, so will wait until you’re done.

**Comment by aovestdipaperino** [comment]
> Fixed, Got ReProvision working. Still need some cleanup, PR soon...
> EDIT: Windows Signing is unsupported, more effort need to be committed.

If the code to sign in doesn't require JB, the authentication could be done on iOS and the token sent to a desktop app.

**Comment by aovestdipaperino** [comment]
Idea: is it possible to patch akd so that the certificate chain is not validated and look at the HTTPS traffic?

**Comment by TrungNguyen1909** [comment]
My code use AuthKit heavily, which required both an Apple device and jailbreak. Unfortunately, on macOS, SIP disabled for amfid patch is required. Partial/full reverse engineering of AuthKit is required for Windows & SIP-enabled Macs

**Comment by pdso** [comment]
@TrungNguyen1909 Awesome, Wating your PR.

**Comment by rileytestut** [comment]
@aovestdipaperino Yes indeed it is! You can swizzle `+[AKCertificatePinning isValidCertificateTrust: forHostname:]` to just return YES, and then you should be able inspect the network traffic. Doing that myself on my Mac (but needs SIP and amfi disabled)

**Comment by TrungNguyen1909** [comment]
Pull Request opened.
I didn't test it carefully, be warned.
I didn't bump the version yet, could @Matchstic handle that for me after everything is ok? [Thanks](https://drive.google.com/open?id=1rSDz36UcKeZh7bpJy78KesPH1nYmHPrL)

**Comment by Samgisaninja** [comment]
so I haven't really paid attention to this and y'all may already be to the point where this is not helpful, but there's a macOS CLI tool, [xcode-install](https://github.com/xcpretty/xcode-install) which is basically a tool that lets you manage Xcode and command line tools versions on your Mac via terminal

During the install process, it requests you log in with an Apple ID/password, and if you have 2FA, it actually lets you input a 2FA code (directly into stdin) instead of requiring an app-specific password

I have no technical information about how this works, and given that a temporary workaround already seems to be in the works, that might be useless for y'all, but I figured it was worth mentioning.

**Comment by kabiroberai** [comment]
@Samgisaninja xcode-install appears to use fastlane, which uses Apple's web auth API (`https://idmsa.apple.com/appleauth/auth`). That API returns a `myacinfo` key which was what ReProvision and similar tools used, however from what I can tell Apple now enforces the GrandSlam API (`https://gsa.apple.com/grandslam/GsService2`) for free accounts.

**Comment by TrungNguyen1909** [comment]
The GrandSlam API seems to require device's serial number. Although the serial number has been forged for a long time in hackintosh community, It's still pose a concern that using fake serial can cause account lock(forced password change). Also, authentication requires 3 Post request filled with xml plist and bunch of encrypted(?) data. akd seems to be linked with MobileKeyBag and AppleIDAuthSupport(iirc) frameworks. Sounds like a long challenge for windows signing. Sorry but I dont have any motivation to do windows signing coz i use macOS so i cant help anybody with windows problem.

**Comment by aovestdipaperino** [comment]
I found a repo containing a bunch of RE stuff, enough to put everything together.

**Comment by the1after** [comment]
I see that reprovision is working, amazing job! But as for some or many of us, we depend on windows cydia impactor. Any new info on it? We appreciate all the work & time put in!

**Comment by TrungNguyen1909** [comment]
> I see that reprovision is working, amazing job! But as for some or many of us, we depend on windows cydia impactor. Any new info on it? We appreciate all the work & time put in! @rileytestut @TrungNguyen1909

We use macOS so we can't help you with your Windows problem. 
No, we don't have impactor's source code. Only saurik can fix that. Please stop asking.
Thanks

**Comment by wxq491216** [comment]
got Unknown error when login with an appleid on jailbreak device.

`
2019-11-18 14:52:48.043098+0800 ReProvision[5125:3324102] [core] Remote authentication service returned an error: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.ak.auth.xpc" UserInfo={NSDebugDescription=connection to service named com.apple.ak.auth.xpc} `
`2019-11-18 14:52:48.043399+0800 ReProvision[5125:3324102] AUTHENTICATE WITH CONTEXT arg1: (null), arg2: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.ak.auth.xpc" UserInfo={NSDebugDescription=connection to service named com.apple.ak.auth.xpc} `
`2019-11-18 14:52:50.472984+0800 ReProvision[5125:3324102] [core] Connection to akd was interrupted!`

**Comment by SarveshAj420** [comment]
Hello Guys,
I have an Iphone XS IOS 12.2. It was jailbroken for a long time and now I am missing it as I am repeatedly getting the error "Please update to Xcode 7.3 or later to continue developing with your Apple ID", whenever i try to jailbreak it. I normally use Cydia Impactor on Mac and also had Reprovision but due to this problem none are working and I am not being able to jailbreak my phone. Can anybody please help me out !!!........

**Comment by xMarkSt** [comment]
> Hello Guys,
> I have an Iphone XS IOS 12.2. It was jailbroken for a long time and now I am missing it as I am repeatedly getting the error "Please update to Xcode 7.3 or later to continue developing with your Apple ID", whenever i try to jailbreak it. I normally use Cydia Impactor on Mac and also had Reprovision but due to this problem none are working and I am not being able to jailbreak my phone. Can anybody please help me out !!!........

Hi,
Are you running the latest version of ReProvision? It is working for me. 
As for cydia impactor, I think it is broken at the moment as far as I know.

**Comment by SarveshAj420** [comment]
> > Hello Guys,
> > I have an Iphone XS IOS 12.2. It was jailbroken for a long time and now I am missing it as I am repeatedly getting the error "Please update to Xcode 7.3 or later to continue developing with your Apple ID", whenever i try to jailbreak it. I normally use Cydia Impactor on Mac and also had Reprovision but due to this problem none are working and I am not being able to jailbreak my phone. Can anybody please help me out !!!........
> 
> Hi,
> Are you running the latest version of ReProvision? It is working for me.
> As for cydia impactor, I think it is broken at the moment as far as I know.

I had ReProvision, as now my device is unjailbroken I cannot access the app. Is there any other way I can access ReProvision while my device is   unjailbroken or side load ReProvision again somehow.

**Comment by DeafEyeJedi** [comment]
You’ll have to rejailbreak with using uncover from OTA downloads (and then go into cydia to update ReProvision. 

Once that’s done, then you can re-download from uncover website directly which then will prompt you w a window to allow for install via ReProvision. 

Also I noticed with the latest ReProvision you will need to log in with normal AppleID and normal password. Not the app-specific password as it used to be. Just beware.

-Sean

**Comment by DeafEyeJedi** [comment]
Here’s a screen record of what you can do after you JB again...

**Comment by SarveshAj420** [comment]
> You’ll have to rejailbreak with using uncover from OTA downloads (and then go into cydia to update ReProvision. Once that’s done, then you can re-download from uncover website directly which then will prompt you w a window to allow for install via ReProvision. Also I noticed with the latest ReProvision you will need to log in with normal AppleID and normal password. Not the app-specific password as it used to be. Just beware.
> […](#)
> -Sean
> Sent from my iPhone XR
> On Nov 18, 2019, at 3:14 PM, SarveshAj420 ***@***.***> wrote: Hello Guys, I have an Iphone XS IOS 12.2. It was jailbroken for a long time and now I am missing it as I am repeatedly getting the error "Please update to Xcode 7.3 or later to continue developing with your Apple ID", whenever i try to jailbreak it. I normally use Cydia Impactor on Mac and also had Reprovision but due to this problem none are working and I am not being able to jailbreak my phone. Can anybody please help me out !!!........ Hi, Are you running the latest version of ReProvision? It is working for me. As for cydia impactor, I think it is broken at the moment as far as I know. I had ReProvision, as now my device is unjailbroken I cannot access the app. Is there any other way I can access ReProvision while my device is unjailbroken or side load ReProvision again somehow. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry but can you please help me on how to rejailbreak using uncover from OTA downloads

**Comment by fatlao** [comment]
> > You’ll have to rejailbreak with using uncover from OTA downloads (and then go into cydia to update ReProvision. Once that’s done, then you can re-download from uncover website directly which then will prompt you w a window to allow for install via ReProvision. Also I noticed with the latest ReProvision you will need to log in with normal AppleID and normal password. Not the app-specific password as it used to be. Just beware.
> > […](#)
> > -Sean
> > Sent from my iPhone XR
> > On Nov 18, 2019, at 3:14 PM, SarveshAj420 _**@**_.***> wrote: Hello Guys, I have an Iphone XS IOS 12.2. It was jailbroken for a long time and now I am missing it as I am repeatedly getting the error "Please update to Xcode 7.3 or later to continue developing with your Apple ID", whenever i try to jailbreak it. I normally use Cydia Impactor on Mac and also had Reprovision but due to this problem none are working and I am not being able to jailbreak my phone. Can anybody please help me out !!!........ Hi, Are you running the latest version of ReProvision? It is working for me. As for cydia impactor, I think it is broken at the moment as far as I know. I had ReProvision, as now my device is unjailbroken I cannot access the app. Is there any other way I can access ReProvision while my device is unjailbroken or side load ReProvision again somehow. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Sorry but can you please help me on how to rejailbreak using uncover from OTA downloads

If you have a mac, you can follow this to resign uncover or chirema.

https://www.reddit.com/r/jailbreak/comments/dw3z3g/news_workaround_for_impactor_xcode_73_error/

**Comment by Waillianm** [comment]
> > I see that reprovision is working, amazing job! But as for some or many of us, we depend on windows cydia impactor. Any new info on it? We appreciate all the work & time put in! @rileytestut @TrungNguyen1909
> 
> We use macOS so we can't help you with your Windows problem.
> No, we don't have impactor's source code. Only saurik can fix that. Please stop asking.
> Thanks

Is there a web version of the login interface resolution?

**Comment by Waillianm** [comment]
spaceship  has API for apple auth, why not use it?

**Comment by mrkiko** [comment]
Sorry for the off topic but...
REPROVISION, Error, updateCurrentTeamIDWithCompletionHandler: No Team ID present! This is *really* bad.

**Comment by Matchstic** [comment]
This particular issue is now resolved. Anything that is NOT related to "Update to Xcode 7.3" should be redirected to a different issues.
